import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd(),errors=[];const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const sourceClasses=['OFFICIAL_STANDARD','OFFICIAL_VENDOR','PROPOSAL','MEASURED','INTERNAL_HEURISTIC','EXPERIMENTAL'];
const required=['assets/css/authority.css','assets/css/site-ia.css','assets/js/authority-tool.js','sitemap.xml','llms.txt','index.md','openapi.json','audit-profile.json','sources.json','scripts/check-source-registry.mjs','.github/workflows/source-registry.yml','.github/workflows/firebase-production.yml','functions-firebase/package.json','functions-firebase/src/index.ts','functions-firebase/scripts/sync-engine.mjs','en/methodology/index.html','tr/methodology/index.html','en/evidence-standard/index.html','tr/kanit-standardi/index.html','en/reference/ai-crawlers/index.html','tr/referans/ai-tarayicilar/index.html'];
for(const rel of required)if(!fs.existsSync(path.join(root,rel)))errors.push(`missing authority file: ${rel}`);
const toolJs=read('assets/js/authority-tool.js');if(!/\/api\/scan/.test(toolJs))errors.push('authority tool must call shared /api/scan');
for(const rel of ['en/methodology/index.html','tr/methodology/index.html']){const t=read(rel);for(const token of [...sourceClasses,'NOT_MEASURED','SSRF'])if(!t.includes(token))errors.push(`${rel} missing ${token}`)}
const profile=JSON.parse(read('audit-profile.json'));if(profile.status!=='public-product-profile')errors.push('audit profile must state public-product-profile status');if(!/not an IETF, W3C/i.test(profile.disclaimer||''))errors.push('audit profile must reject third-party standard implication');
const canonicalEngine=read('functions/lib/scan-engine.ts');const wm=canonicalEngine.match(/const overallWeights:Record<Category,number>=\{([^}]+)\}/);if(!wm)errors.push('canonical scan engine overallWeights not parseable');else{const canonicalWeights={};for(const m of wm[1].matchAll(/(\w+):(\d+)/g))canonicalWeights[m[1]]=Number(m[2]);const publicWeights=Object.fromEntries((profile.engines||[]).map(x=>[x.id,x.overallWeight]));for(const [id,w] of Object.entries(canonicalWeights))if(publicWeights[id]!==w)errors.push(`public audit profile weight drift: ${id}`);if(Object.values(publicWeights).reduce((a,b)=>a+Number(b),0)!==100)errors.push('public audit profile weights must total 100')}
const registry=JSON.parse(read('sources.json'));const ids=new Set();for(const s of registry.sources||[]){if(!s.id||ids.has(s.id))errors.push(`source registry duplicate/missing id: ${s.id}`);ids.add(s.id);if(!sourceClasses.includes(s.class))errors.push(`source registry class outside scanner model: ${s.id}/${s.class}`);if(!String(s.url||'').startsWith('https://'))errors.push(`source registry non-https URL: ${s.id}`)}for(const id of ['RFC9309','OPENAI-SEARCH','OPENAI-PUBLISHERS','ANTHROPIC-CRAWLERS','PERPLEXITY-ROBOTS','GOOGLE-COMMON-CRAWLERS','LLMS-TXT-V2','LLMS-TXT-CHANGES'])if(!ids.has(id))errors.push(`source registry missing decision source: ${id}`);
const openapi=JSON.parse(read('openapi.json'));if(openapi.openapi!=='3.1.0')errors.push('OpenAPI must be 3.1.0');for(const route of ['/api/health','/api/scan','/api/mentions','/api/mandate'])if(!openapi.paths?.[route])errors.push(`OpenAPI missing ${route}`);
const firebase=JSON.parse(read('firebase.json'));const rewrites=firebase.hosting?.rewrites||[];for(const route of ['/api/health','/api/scan','/api/mentions','/api/mandate'])if(!rewrites.some(r=>r.source===route&&r.function?.functionId))errors.push(`Firebase missing API rewrite ${route}`);if(!Array.isArray(firebase.functions)||firebase.functions[0]?.source!=='functions-firebase')errors.push('Firebase functions source not configured');
const adapter=read('functions-firebase/src/index.ts');if(!adapter.includes("from './scan-request'"))errors.push('Firebase adapter must consume synced canonical scan wrapper');const sync=read('functions-firebase/scripts/sync-engine.mjs');if(!sync.includes('../functions/lib/')||!sync.includes('scan-engine.ts')||!sync.includes('scan-request.ts'))errors.push('Firebase sync must source canonical scan engine and request wrapper');
const sitemap=read('sitemap.xml'),llms=read('llms.txt');for(const r of ['/en','/tr','/en/tools','/tr/araclar','/en/guides','/tr/rehberler','/en/methodology','/tr/methodology','/en/evidence-standard','/tr/kanit-standardi','/en/reference/ai-crawlers','/tr/referans/ai-tarayicilar']){if(!sitemap.includes(`https://htmlandhtml.com${r}`))errors.push(`sitemap missing ${r}`);if(!llms.includes(`https://htmlandhtml.com${r}`))errors.push(`llms.txt missing ${r}`)}
if(!llms.includes('https://htmlandhtml.com/audit-profile.json'))errors.push('llms.txt missing audit profile JSON');if(!llms.includes('https://htmlandhtml.com/sources.json'))errors.push('llms.txt missing source registry JSON');if(!llms.includes('https://htmlandhtml.com/openapi.json'))errors.push('llms.txt missing OpenAPI contract');if(!/Unknown or unavailable measurements are excluded/i.test(llms))errors.push('llms.txt missing unknown-score boundary');
if(fs.existsSync(path.join(root,'.well-known/agent-card.json'))||fs.existsSync(path.join(root,'mcp')))errors.push('Do not add fake A2A/MCP surfaces merely to improve score');
if(errors.length){console.error('AUTHORITY INTEGRITY FAIL');for(const e of errors)console.error(`- ${e}`);process.exit(1)}console.log('AUTHORITY INTEGRITY PASS: localized methodology, evidence governance, canonical weights, source registry, OpenAPI and Firebase topology verified.');
