import fs from 'node:fs';
const read=p=>fs.readFileSync(p,'utf8');const exists=p=>fs.existsSync(p);const errors=[];
const pairs=[["/en","/tr"],["/en/platform","/tr/platform"],["/en/tools","/tr/araclar"],["/en/guides","/tr/rehberler"],["/en/website-scanner","/tr/site-tarama"],["/en/ai-website-readiness","/tr/ai-website-readiness"],["/en/llms-txt-validator","/tr/llms-txt-validator"],["/en/ai-crawler-checker","/tr/ai-crawler-checker"],["/en/schema-validator","/tr/schema-validator"],["/en/technical-seo-checker","/tr/teknik-seo-kontrol"],["/en/security-headers-checker","/tr/guvenlik-basliklari-kontrol"],["/en/accessibility-checker","/tr/erisilebilirlik-kontrol"],["/en/link-integrity-checker","/tr/link-kontrol"],["/en/ai-mention-tracker","/tr/ai-mention-tracker"],["/en/fix-mandate","/tr/fix-mandate"],["/en/pricing","/tr/fiyatlandirma"],["/en/methodology","/tr/methodology"],["/en/evidence-standard","/tr/kanit-standardi"],["/en/reference/ai-crawlers","/tr/referans/ai-tarayicilar"],["/en/guides/ai-website-readiness-checklist","/tr/rehberler/ai-web-sitesi-hazirlik-kontrol-listesi"],["/en/guides/llms-txt","/tr/rehberler/llms-txt"],["/en/guides/ai-crawler-access","/tr/rehberler/ai-tarayici-erisimi"],["/en/guides/structured-data-for-ai","/tr/rehberler/ai-icin-yapisal-veri"],["/en/guides/ai-search-visibility","/tr/rehberler/ai-arama-gorunurlugu"],["/en/about","/tr/hakkimizda"],["/en/contact","/tr/iletisim"],["/en/privacy","/tr/gizlilik"],["/en/terms","/tr/kullanim-kosullari"]];
for(const [en,tr] of pairs){for(const [route,lang,alt] of [[en,'en',tr],[tr,'tr',en]]){const rel=route.slice(1)+'/index.html';if(!exists(rel)){errors.push('missing '+rel);continue}const s=read(rel);if(!s.includes('<html lang="'+lang+'"'))errors.push(rel+': lang');if(!s.includes('rel="canonical" href="https://htmlandhtml.com'+route+'"'))errors.push(rel+': canonical');if(!s.includes('hreflang="'+(lang==='en'?'tr':'en')+'" href="https://htmlandhtml.com'+alt+'"'))errors.push(rel+': hreflang');if(!s.includes('BreadcrumbList')&&!['/en','/tr'].includes(route))errors.push(rel+': breadcrumb schema');if(/\?lang=(en|tr)/.test(s))errors.push(rel+': query-language link');}}
const firebase=JSON.parse(read('firebase.json'));if(!firebase.hosting.redirects.some(x=>x.source==='/'&&x.destination==='/en'&&x.type===301))errors.push('root must 301 to /en');
const sitemap=read('sitemap.xml'),llms=read('llms.txt');for(const [en,tr] of pairs)for(const r of [en,tr]){if(!sitemap.includes('https://htmlandhtml.com'+r))errors.push('sitemap missing '+r);if(!llms.includes('https://htmlandhtml.com'+r))errors.push('llms missing '+r)}
for(const hub of ['en/index.html','tr/index.html']){const s=read(hub);for(const token of ['/platform','/tools','/araclar','/guides','/rehberler']){/* structural coverage below */}if(!s.includes('toolScanForm'))errors.push(hub+': scanner missing');if(!s.includes('site-ia.css'))errors.push(hub+': IA css missing')}
const en=read('en/index.html'),tr=read('tr/index.html');for(const r of ['/en/platform','/en/tools','/en/guides','/en/pricing'])if(!en.includes('href="'+r+'"'))errors.push('EN hub missing '+r);for(const r of ['/tr/platform','/tr/araclar','/tr/rehberler','/tr/fiyatlandirma'])if(!tr.includes('href="'+r+'"'))errors.push('TR hub missing '+r);
for(const p of ['assets/css/site-ia.css','scripts/build-enterprise-ia.mjs'])if(!exists(p))errors.push('missing '+p);
if(errors.length){console.error('ENTERPRISE IA FAIL');for(const e of errors)console.error('- '+e);process.exit(1)}console.log('ENTERPRISE IA PASS: locale hubs, intent pages, hreflang/canonical graph, sitemap, llms and root migration verified.');
