import fs from 'node:fs';
import assert from 'node:assert/strict';
const ui=fs.readFileSync('assets/js/r10-quality-hotfix.js','utf8');
const fn=fs.readFileSync('functions-firebase/src/index.ts','utf8');
const telemetry=fs.readFileSync('functions-firebase/src/scan-telemetry.ts','utf8');
const admin=fs.readFileSync('admin/index.html','utf8');
const cache=fs.readFileSync('scripts/patch_r10_quality_cache.py','utf8');
assert.match(ui,/RFC 9309 — Robots Exclusion Protocol/);
assert.match(ui,/NOT_MEASURED/);
assert.match(ui,/Bu bulgu bir AI bot erişim testi değildir/);
assert.match(fn,/googlebot\.category='crawl'/);
assert.match(fn,/weightedScore\(/);
assert.match(fn,/recordScanTelemetry/);
assert.match(telemetry,/PBKDF2_ITERATIONS=600_000/);
assert.match(telemetry,/timingSafeEqual/);
assert.doesNotMatch(telemetry,/req\.ip|x-forwarded-for|user-agent/i);
assert.match(admin,/noindex,nofollow,noarchive,nosnippet/);
assert.match(admin,/type="password"/);
assert.doesNotMatch(admin,/localStorage|sessionStorage/);
assert.match(cache,/quality=002/);
assert.match(cache,/r10-quality-hotfix/);
console.log('R10_QUALITY_ADMIN_GUARD_PASS');
