import fs from 'node:fs';
import assert from 'node:assert/strict';
const positioning=fs.readFileSync('assets/js/ai-positioning.js','utf8');
const ui=fs.readFileSync('assets/js/r10-quality-hotfix.js','utf8');
const r10Style=fs.readFileSync('assets/css/r10-report-ux.css','utf8');
const fn=fs.readFileSync('functions-firebase/src/index.ts','utf8');
const telemetry=fs.readFileSync('functions-firebase/src/scan-telemetry.ts','utf8');
const engine=fs.readFileSync('functions/lib/scan-engine.ts','utf8');
const admin=fs.readFileSync('admin/index.html','utf8');
const adminApp=(admin.split('</head>')[1]||admin);
const cache=fs.readFileSync('scripts/patch_r10_quality_cache.py','utf8');
assert.match(positioning,/2026-09-10T20:55:00Z/);
assert.match(positioning,/10 Eylül 23:55/);
assert.match(ui,/2026-09-10T20:55:00Z/);
assert.match(ui,/RFC 9309 — Robots Exclusion Protocol/);
assert.match(ui,/NOT_MEASURED/);
assert.match(ui,/Bu bulgu bir AI bot erişim testi değildir/);
assert.match(ui,/function setText\(el,text\)\{if\(el&&el\.textContent!==text\)el\.textContent=text\}/);
assert.match(ui,/new MutationObserver\(scheduleSweep\)/);
assert.match(ui,/requestAnimationFrame\(\(\)=>\{sweepQueued=false;sweep\(\)\}\)/);
assert.doesNotMatch(ui,/if\(badge\)badge\.textContent=/);
assert.doesNotMatch(ui,/if\(h\)h\.textContent=/);
assert.doesNotMatch(ui,/if\(p\)p\.textContent=/);
assert.match(r10Style,/html\[data-theme="light"\] #result \.hh-evidence-block/);
assert.match(r10Style,/background: #ffffff !important/);
assert.match(r10Style,/color: #0f172a !important/);
assert.match(r10Style,/html\.hh-r10-open #result \.locked-fix-overlay/);
assert.match(r10Style,/html\.hh-r10-open #result \.recipe-section\.locked \.recipe-overlay/);
assert.match(r10Style,/html\.hh-r10-open #result \.recipe-section\.locked \.recipe-content/);
assert.match(r10Style,/filter: none !important/);
assert.match(r10Style,/pointer-events: auto !important/);
assert.match(fn,/googlebot\.category='crawl'/);
assert.match(fn,/weightedScore\(/);
assert.match(fn,/recordScanTelemetry/);
assert.match(telemetry,/ADMIN_PBKDF2_ITERATIONS=600_000/);
assert.match(telemetry,/timingSafeEqual/);
assert.match(telemetry,/ADMIN_MAX_FAILURES=5/);
assert.match(telemetry,/TELEMETRY_RESPONSE_BUDGET_MS=650/);
assert.match(telemetry,/Promise\.race\(\[pending,new Promise<void>/);
assert.doesNotMatch(telemetry,/TELEMETRY_RESPONSE_BUDGET_MS=[1-9]\d{3,}/);
assert.doesNotMatch(telemetry,/Deneme1974/);
assert.doesNotMatch(telemetry,/req\.ip|x-forwarded-for|user-agent/i);
assert.match(engine,/MAX_PAGES=50,MAX_LINK_PROBES=30,TIMEOUT_MS=7000,PROBE_CONCURRENCY=4/);
assert.match(engine,/async function probeMany\(urls:string\[\]\)/);
assert.match(engine,/await probeMany\(llmsTargets\)/);
assert.match(engine,/await probeMany\(probeSet\)/);
assert.doesNotMatch(engine,/for\(const href of probeSet\)\{const s=await probe\(href\)/);
assert.doesNotMatch(engine,/for\(const l of linked\)\{[^}]*await probe\(u\)/s);
assert.match(admin,/noindex,nofollow,noarchive,nosnippet/);
assert.match(admin,/type="password"/);
assert.doesNotMatch(adminApp,/localStorage|sessionStorage/);
assert.match(cache,/r10-20260910-2355&amp;quality=005/);
assert.match(cache,/r10-quality-hotfix\.js\?v=20260910-005/);
assert.match(cache,/r10-report-ux\.css\?v=20260910-001/);
console.log('R10_QUALITY_ADMIN_GUARD_PASS');
