import {createHash,pbkdf2Sync,timingSafeEqual,randomInt} from 'node:crypto';
import {getApps,initializeApp} from 'firebase-admin/app';
import {FieldValue,getFirestore,Timestamp} from 'firebase-admin/firestore';

const SHARDS=16;
const SUMMARY_COLLECTION='htmlhtml_scan_stats_shards';
const DOMAIN_COLLECTION='htmlhtml_scan_domain_stats';
const ADMIN_PBKDF2_ITERATIONS=600_000;
const ADMIN_PBKDF2_SALT_B64='TqZ0rX6uxYvJm3NCtNfAtQ==';
const ADMIN_PBKDF2_HASH_B64='h2f1x52xxxV75xziiAO5E74ykgbK2fMhuovvnF1lx30=';

export type ScanTelemetryInput={success:boolean;domain?:string;durationMs:number;pagesScanned?:number;linksProbed?:number;findingCount?:number;overall?:number;errorClass?:'invalid_request'|'blocked_target'|'dns'|'timeout'|'scan_error'};
function firestore(){if(!getApps().length)initializeApp();return getFirestore()}
function safeInt(value:unknown){const n=Number(value);return Number.isFinite(n)&&n>0?Math.round(n):0}
function cleanDomain(value:string|undefined){if(!value)return '';const host=value.trim().toLowerCase().replace(/^https?:\/\//,'').split('/')[0].split('?')[0].split('#')[0];return /^[a-z0-9.-]+$/.test(host)&&host.length<=253?host:''}
function domainDocId(domain:string){return createHash('sha256').update(domain).digest('hex')}
export function classifyScanError(message:string):ScanTelemetryInput['errorClass']{const m=String(message||'').toLowerCase();if(/required|invalid url|only http/.test(m))return 'invalid_request';if(/not allowed|private|reserved|credentials|port|localhost/.test(m))return 'blocked_target';if(/dns|resolution/.test(m))return 'dns';if(/timeout|timed out|abort/.test(m))return 'timeout';return 'scan_error'}
export async function recordScanTelemetry(input:ScanTelemetryInput){const db=firestore();const shard=String(randomInt(0,SHARDS)).padStart(2,'0');const duration=Math.max(0,safeInt(input.durationMs));const pages=safeInt(input.pagesScanned),links=safeInt(input.linksProbed),findings=safeInt(input.findingCount);const summary:Record<string,unknown>={totalRequests:FieldValue.increment(1),totalDurationMs:FieldValue.increment(duration),lastRequestAt:FieldValue.serverTimestamp(),telemetryVersion:1};if(input.success){summary.successfulScans=FieldValue.increment(1);summary.totalPagesScanned=FieldValue.increment(pages);summary.totalLinksProbed=FieldValue.increment(links);summary.totalFindings=FieldValue.increment(findings);summary.lastSuccessAt=FieldValue.serverTimestamp()}else{summary.failedScans=FieldValue.increment(1);summary.lastFailureAt=FieldValue.serverTimestamp();if(input.errorClass)summary[`failure_${input.errorClass}`]=FieldValue.increment(1)}const writes:Promise<unknown>[]=[db.collection(SUMMARY_COLLECTION).doc(shard).set(summary,{merge:true})];const domain=cleanDomain(input.domain);if(input.success&&domain)writes.push(db.collection(DOMAIN_COLLECTION).doc(domainDocId(domain)).set({domain,scans:FieldValue.increment(1),totalPagesScanned:FieldValue.increment(pages),totalLinksProbed:FieldValue.increment(links),totalFindings:FieldValue.increment(findings),totalDurationMs:FieldValue.increment(duration),lastOverall:typeof input.overall==='number'?Math.round(input.overall):null,lastFindingCount:findings,lastScannedAt:FieldValue.serverTimestamp(),telemetryVersion:1},{merge:true}));await Promise.all(writes)}
function ts(value:unknown){if(value instanceof Timestamp)return value.toDate().toISOString();if(value&&typeof value==='object'&&'toDate' in value&&typeof (value as {toDate?:unknown}).toDate==='function'){try{return ((value as {toDate:()=>Date}).toDate()).toISOString()}catch{return null}}return null}
function verifyPassword(input:unknown){if(typeof input!=='string'||input.length<8||input.length>128)return false;const salt=Buffer.from(ADMIN_PBKDF2_SALT_B64,'base64'),expected=Buffer.from(ADMIN_PBKDF2_HASH_B64,'base64');const actual=pbkdf2Sync(input,salt,ADMIN_PBKDF2_ITERATIONS,expected.length,'sha256');return actual.length===expected.length&&timingSafeEqual(actual,expected)}
export async function readAdminStats(password:unknown){if(!verifyPassword(password))return {ok:false as const,status:401 as const,error:'Yetkisiz erişim.'};const db=firestore();const [shards,domains,countAgg]=await Promise.all([db.collection(SUMMARY_COLLECTION).get(),db.collection(DOMAIN_COLLECTION).orderBy('scans','desc').limit(500).get(),db.collection(DOMAIN_COLLECTION).count().get()]);const totals={totalRequests:0,successfulScans:0,failedScans:0,totalPagesScanned:0,totalLinksProbed:0,totalFindings:0,totalDurationMs:0,failure_invalid_request:0,failure_blocked_target:0,failure_dns:0,failure_timeout:0,failure_scan_error:0};let lastRequestAt:string|null=null,lastSuccessAt:string|null=null,lastFailureAt:string|null=null;for(const doc of shards.docs){const d=doc.data() as Record<string,unknown>;for(const key of Object.keys(totals) as Array<keyof typeof totals>)totals[key]+=safeInt(d[key]);for(const field of ['lastRequestAt','lastSuccessAt','lastFailureAt'] as const){const value=ts(d[field]);if(!value)continue;if(field==='lastRequestAt'&&(!lastRequestAt||value>lastRequestAt))lastRequestAt=value;if(field==='lastSuccessAt'&&(!lastSuccessAt||value>lastSuccessAt))lastSuccessAt=value;if(field==='lastFailureAt'&&(!lastFailureAt||value>lastFailureAt))lastFailureAt=value}}const rows=domains.docs.map(doc=>{const d=doc.data() as Record<string,unknown>,scans=safeInt(d.scans),duration=safeInt(d.totalDurationMs);return {domain:String(d.domain||''),scans,lastScannedAt:ts(d.lastScannedAt),lastOverall:typeof d.lastOverall==='number'?Math.round(d.lastOverall):null,lastFindingCount:safeInt(d.lastFindingCount),totalPagesScanned:safeInt(d.totalPagesScanned),totalLinksProbed:safeInt(d.totalLinksProbed),avgDurationMs:scans?Math.round(duration/scans):0}});return {ok:true as const,status:200 as const,generatedAt:new Date().toISOString(),historyBoundary:'İstatistikler bu telemetri sürümü canlıya alındıktan sonraki taramaları kapsar.',summary:{...totals,uniqueDomains:Number(countAgg.data().count||0),successRatePct:totals.totalRequests?Math.round((totals.successfulScans/totals.totalRequests)*1000)/10:0,avgDurationMs:totals.totalRequests?Math.round(totals.totalDurationMs/totals.totalRequests):0,lastRequestAt,lastSuccessAt,lastFailureAt},domains:rows}}
