/**
 * HTML&HTML Enterprise AI Intelligence — Canonical Rules Registry
 * Document Code: HTMLHTML-EAI-2026-V4 (Section 2.2 & Section 5)
 */

import type { EvidenceClass } from './evidence-classes.ts';

export type PlaneType = 'TECHNICAL' | 'OBSERVATION' | 'DECISION';

export interface CanonicalRuleRecord {
  ruleId: string;
  version: string;
  title: string;
  plane: PlaneType;
  evidenceClass: EvidenceClass;
  sourceIds: string[];
  applicability: string[];
  measurement: string;
  failureMeaning: string;
  scoreImpact: number | null;
  confidencePolicy: string;
  lastVerifiedAt: string;
  maxSourceAgeDays: number;
}

export const CANONICAL_RULES: CanonicalRuleRecord[] = [
  // PLANE A: TECHNICAL READINESS
  {
    ruleId: 'RULE-HSTS-001',
    version: '1.0.0',
    title: 'Strict-Transport-Security (HSTS) Header Enforcement & Preload',
    plane: 'TECHNICAL',
    evidenceClass: 'OFFICIAL_STANDARD',
    sourceIds: ['RFC6797'],
    applicability: ['production', 'https', 'all-domains'],
    measurement: 'HTTP response header verification on edge endpoints.',
    failureMeaning: 'Missing HSTS exposes domain to SSL-stripping and downgrades trust ratings in enterprise AI security crawlers.',
    scoreImpact: 15,
    confidencePolicy: 'DETERMINISTIC_EXACT',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 180,
  },
  {
    ruleId: 'RULE-CANON-002',
    version: '1.0.0',
    title: 'RFC 6596 Absolute Canonical Link Self-Declaration',
    plane: 'TECHNICAL',
    evidenceClass: 'OFFICIAL_STANDARD',
    sourceIds: ['RFC6596'],
    applicability: ['html-pages'],
    measurement: 'DOM <link rel="canonical" href="..."> inspection vs current request URI.',
    failureMeaning: 'Missing or relative canonical link causes index fragmentation and citation dilution across LLM training archives.',
    scoreImpact: 12,
    confidencePolicy: 'DETERMINISTIC_EXACT',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 180,
  },
  {
    ruleId: 'RULE-CRAWL-OAI-003',
    version: '1.0.0',
    title: 'OpenAI SearchBot vs GPTBot Purpose Separation in robots.txt',
    plane: 'TECHNICAL',
    evidenceClass: 'OFFICIAL_VENDOR',
    sourceIds: ['OPENAI-PUBLISHERS', 'RFC9309'],
    applicability: ['robots.txt'],
    measurement: 'Effective REP rule evaluation specifically for OAI-SearchBot and GPTBot user agents.',
    failureMeaning: 'Collapsing GPTBot and OAI-SearchBot creates unintended search invisibility or unconsented model training.',
    scoreImpact: 15,
    confidencePolicy: 'DETERMINISTIC_EXACT',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 45,
  },
  {
    ruleId: 'RULE-CRAWL-ANTH-004',
    version: '1.0.0',
    title: 'Anthropic ClaudeBot vs Claude-User vs Claude-SearchBot Granular Directives',
    plane: 'TECHNICAL',
    evidenceClass: 'OFFICIAL_VENDOR',
    sourceIds: ['ANTHROPIC-CRAWLERS', 'RFC9309'],
    applicability: ['robots.txt'],
    measurement: 'Effective REP rule calculation for ClaudeBot, Claude-User, and Claude-SearchBot.',
    failureMeaning: 'Blocking ClaudeBot without allowing Claude-SearchBot drops direct answer retrieval in Claude chat.',
    scoreImpact: 12,
    confidencePolicy: 'DETERMINISTIC_EXACT',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 45,
  },
  {
    ruleId: 'RULE-CRAWL-GOOG-005',
    version: '1.0.0',
    title: 'Google-Extended Non-Ranking Content Control Separation',
    plane: 'TECHNICAL',
    evidenceClass: 'OFFICIAL_VENDOR',
    sourceIds: ['GOOGLE-COMMON-CRAWLERS'],
    applicability: ['robots.txt'],
    measurement: 'Evaluation of Google-Extended directive without penalizing Google Search indexing/ranking.',
    failureMeaning: 'Treating Google-Extended as search ranking signal produces false SEO alarm; it only controls Gemini/Vertex training.',
    scoreImpact: 0,
    confidencePolicy: 'DETERMINISTIC_EXACT',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 45,
  },
  {
    ruleId: 'RULE-PROP-LLMS-006',
    version: '1.0.0',
    title: '/llms.txt Machine Discovery Proposal Evaluation',
    plane: 'TECHNICAL',
    evidenceClass: 'PROPOSAL',
    sourceIds: ['LLMS-TXT-V2'],
    applicability: ['llms.txt'],
    measurement: 'HTTP probe of /.well-known/llms.txt and /llms.txt for markdown structure.',
    failureMeaning: 'Missing llms.txt reduces agent context efficiency but carries NO normative search penalty.',
    scoreImpact: 5,
    confidencePolicy: 'DETERMINISTIC_EXACT',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 60,
  },
  {
    ruleId: 'RULE-SCHEMA-GRAPH-007',
    version: '1.0.0',
    title: 'Unified JSON-LD @graph Entity Topology with Persistent Node IDs',
    plane: 'TECHNICAL',
    evidenceClass: 'OFFICIAL_STANDARD',
    sourceIds: ['SCHEMA-ORG'],
    applicability: ['html-pages'],
    measurement: 'JSON-LD extraction, @graph array verification, #organization and #software URI node linkage.',
    failureMeaning: 'Fragmented schemas produce disconnected knowledge graph fragments in entity grounding engines.',
    scoreImpact: 10,
    confidencePolicy: 'DETERMINISTIC_EXACT',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 90,
  },
  {
    ruleId: 'RULE-AGENT-OPENAPI-008',
    version: '1.0.0',
    title: 'OpenAPI 3.1 Live Interface & Endpoint Documentation',
    plane: 'TECHNICAL',
    evidenceClass: 'OFFICIAL_STANDARD',
    sourceIds: ['OPENAPI31'],
    applicability: ['apis', 'saas'],
    measurement: 'Validation of live OpenAPI 3.1 json/yaml schema against live endpoint responses.',
    failureMeaning: 'Static design without working API endpoint cannot support agentic action execution.',
    scoreImpact: 10,
    confidencePolicy: 'DETERMINISTIC_EXACT',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 180,
  },
  {
    ruleId: 'RULE-AGENT-A2A-009',
    version: '1.0.0',
    title: 'A2A Protocol Agent Card Discovery & Task Execution Capability',
    plane: 'TECHNICAL',
    evidenceClass: 'PROPOSAL',
    sourceIds: ['A2A-SPEC'],
    applicability: ['apis', 'saas', 'agents'],
    measurement: 'Probe of /.well-known/agent-card.json and live capability execution test.',
    failureMeaning: 'Static JSON file without active task execution capability is marked DESIGN_ONLY, not PASS.',
    scoreImpact: 8,
    confidencePolicy: 'DETERMINISTIC_EXACT',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 60,
  },
  {
    ruleId: 'RULE-AGENT-MCP-010',
    version: '1.0.0',
    title: 'Model Context Protocol (MCP) Live Server & Tool Discovery',
    plane: 'TECHNICAL',
    evidenceClass: 'OFFICIAL_STANDARD',
    sourceIds: ['MCP-SPEC'],
    applicability: ['apis', 'saas', 'agents'],
    measurement: 'JSON-RPC tool list and resource discovery over SSE / Streamable HTTP transport.',
    failureMeaning: 'MCP specification without live server or origin validation fails agentic readiness.',
    scoreImpact: 10,
    confidencePolicy: 'DETERMINISTIC_EXACT',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 60,
  },
  {
    ruleId: 'RULE-C2PA-PROV-011',
    version: '1.0.0',
    title: 'C2PA Signed Content Credentials Verification',
    plane: 'TECHNICAL',
    evidenceClass: 'OFFICIAL_STANDARD',
    sourceIds: ['C2PA-SPEC'],
    applicability: ['digital-media', 'images', 'articles'],
    measurement: 'Verification of embedded or manifest-bound C2PA JUMBF cryptographic signatures.',
    failureMeaning: 'Fake JSON-LD c2pa fields without cryptographic manifest fail as NOT_IMPLEMENTED.',
    scoreImpact: 8,
    confidencePolicy: 'DETERMINISTIC_EXACT',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 90,
  },
  {
    ruleId: 'RULE-GOV-TDM-012',
    version: '1.0.0',
    title: 'EU TDM Directive 2019/790 Article 4 Machine-Readable Rights Reservation',
    plane: 'TECHNICAL',
    evidenceClass: 'OFFICIAL_STANDARD',
    sourceIds: ['EU-TDM-DIR2019-790'],
    applicability: ['all-domains', 'content-publishers'],
    measurement: 'Inspection of HTTP headers, robots directives, and metadata for express TDM reservation.',
    failureMeaning: 'Failure to express TDM reservation permits unconstrained commercial scraping in EU jurisdiction.',
    scoreImpact: 6,
    confidencePolicy: 'DETERMINISTIC_EXACT',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 180,
  },

  // PLANE B: OBSERVED AI ANSWER INTELLIGENCE
  {
    ruleId: 'RULE-OBS-MENTION-020',
    version: '1.0.0',
    title: 'Observed AI Answer Brand Mention Rate Across Prompt Panel',
    plane: 'OBSERVATION',
    evidenceClass: 'OBSERVED',
    sourceIds: ['OPENAI-PUBLISHERS', 'PERPLEXITY-ROBOTS'],
    applicability: ['enterprise-ai-observatory'],
    measurement: 'Up to 3 neutral configured queries per run across available provider surfaces. Grounding/search use is observed and reported; search must not be forced solely to manufacture citation data.',
    failureMeaning: 'Brand absence is an observed sample outcome for the configured prompt set; it does not prove zero market awareness or zero visibility outside the sample.',
    scoreImpact: null,
    confidencePolicy: 'MULTI_RUN_SAMPLE_WEIGHTED',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 30,
  },
  {
    ruleId: 'RULE-OBS-CITATION-021',
    version: '1.0.0',
    title: 'Observed AI Answer Citation & Source Link Match Rate',
    plane: 'OBSERVATION',
    evidenceClass: 'OBSERVED',
    sourceIds: ['OPENAI-PUBLISHERS', 'PERPLEXITY-ROBOTS'],
    applicability: ['enterprise-ai-observatory'],
    measurement: 'Extraction and domain matching of citations or source links actually returned by the configured provider surface, with grounding/search state recorded separately when available.',
    failureMeaning: 'Absence of a citation in the sampled response means no direct citation referral was observed in that response; it does not establish platform-wide absence.',
    scoreImpact: null,
    confidencePolicy: 'MULTI_RUN_SAMPLE_WEIGHTED',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 30,
  },
  {
    ruleId: 'RULE-OBS-RECOMMEND-022',
    version: '1.0.0',
    title: 'Observed Competitive Recommendation Rate & Share of Answer',
    plane: 'OBSERVATION',
    evidenceClass: 'OBSERVED',
    sourceIds: ['OPENAI-PUBLISHERS', 'PERPLEXITY-ROBOTS'],
    applicability: ['enterprise-ai-observatory'],
    measurement: 'Deterministic classification of brand/competitor mentions inside the configured neutral prompt sample; no forced recommendation prompt is required.',
    failureMeaning: 'A competitor recommendation is an observed sample outcome and must be trended across repeated equivalent prompts before strategic action.',
    scoreImpact: null,
    confidencePolicy: 'MULTI_RUN_SAMPLE_WEIGHTED',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 30,
  },

  // PLANE C: DECISION & REMEDIATION INTELLIGENCE
  {
    ruleId: 'RULE-DEC-ROOT-030',
    version: '1.0.0',
    title: 'Normalized Failure Deduplication & Root Cause Clustering',
    plane: 'DECISION',
    evidenceClass: 'INTERNAL_HEURISTIC',
    sourceIds: [],
    applicability: ['all-audits'],
    measurement: 'Mapping raw telemetry observations into deduplicated engineering interventions.',
    failureMeaning: 'Unclustered issues overwhelm engineering teams with hundreds of redundant symptoms.',
    scoreImpact: null,
    confidencePolicy: 'DETERMINISTIC_GRAPH',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 45,
  },
  {
    ruleId: 'RULE-DEC-PRIORITY-031',
    version: '1.0.0',
    title: 'Opportunity Priority Ranking (Intent x Gap x Capture x Feasibility / Cost)',
    plane: 'DECISION',
    evidenceClass: 'INTERNAL_HEURISTIC',
    sourceIds: [],
    applicability: ['all-audits'],
    measurement: 'Multi-variable opportunity ranking scoring P0 to P3 interventions.',
    failureMeaning: 'Ad-hoc prioritization leads to high engineering cost with negligible AI demand capture.',
    scoreImpact: null,
    confidencePolicy: 'DETERMINISTIC_GRAPH',
    lastVerifiedAt: '2026-09-08',
    maxSourceAgeDays: 45,
  },
];
