import fs from 'node:fs';
import path from 'node:path';

const root=process.cwd();
const files=[];
function walk(dir){if(!fs.existsSync(dir))return;for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())walk(p);else if(e.isFile()&&e.name.endsWith('.html'))files.push(p)}}
walk(path.join(root,'tr'));

// Exact human-copy replacements only. Protocol tokens, API field names, product
// names from third parties, MIME values and URLs remain exact where required.
const replacements=[
 ['AI Mention Tracker — ChatGPT, Perplexity, Gemini Atıf Kontrolü','AI Marka Görünürlük Takibi — ChatGPT, Perplexity, Gemini Kaynak Kontrolü'],
 ['OpenAI web-search, Perplexity Sonar ve Gemini Google Search grounded yanıtlarında','OpenAI web araması, Perplexity Sonar ve Gemini Google Search temellendirmeli yanıtlarında'],
 ['HTML&HTML AI Mention Tracker','HTML&HTML AI Marka Görünürlük Takibi'],
 ['Paid AI mention monitoring module','Ücretli AI marka görünürlük takip modülü'],
 ['AI MENTION TRACKER / PAID MODULE','AI MARKA GÖRÜNÜRLÜK TAKİBİ / ÜCRETLİ MODÜL'],
 ['OpenAI Responses API + web search, Perplexity Sonar ve Gemini + Google Search grounding yüzeylerinde','OpenAI Responses API + web araması, Perplexity Sonar ve Gemini + Google Search temellendirme yüzeylerinde'],
 ['marka mention, domain citation ve kullanılan kaynak URL’lerini','marka anılması, alan adı kaynak gösterimi ve kullanılan kaynak URL’lerini'],
 ['Marka/domain yalnızca sonuçta aranır.','Marka/alan adı yalnızca sonuçta aranır.'],
 ['marka veya domain yazılması','marka veya alan adı yazılması'],
 ['<label for="mentionDomain">Domain</label>','<label for="mentionDomain">Alan adı</label>'],
 ['placeholder="Access key"','placeholder="Erişim anahtarı"'],
 ['llms.txt, AI crawler erişimi ve schema kontrollerini birlikte yapan site audit araçları','llms.txt, AI tarayıcı erişimi ve yapısal veri kontrollerini birlikte yapan site denetim araçları'],
 ['AI website readiness için teknik audit hizmeti veren araçlar','AI web sitesi hazırlığı için teknik denetim hizmeti veren araçlar'],
 ['Mention kontrolünü çalıştır','Anılma kontrolünü çalıştır'],
 ['Access key tarayıcıda kalıcı saklanmaz.','Erişim anahtarı tarayıcıda kalıcı saklanmaz.'],
 ['Markayı prompt’a yazıp “mention” üretmiyoruz.','Markayı isteme yazıp yapay “anılma” üretmiyoruz.'],
 ['Tracker’ın temel kuralı tarafsız sorgudur.','Takip modülünün temel kuralı tarafsız sorgudur.'],
 ['marka veya domain sorguda geçerse','marka veya alan adı sorguda geçerse'],
 ['“prompt injection ile kendini anma” değil, sağlayıcının retrieval/generation davranışındaki organik görünürlüğü','“isteme hedef markayı enjekte ederek kendini anma” değil, sağlayıcının bilgi erişimi/yanıt üretimi davranışındaki organik görünürlüğü'],
 ['Responses + Web Search','Responses API + Web Araması'],
 ['marka/domain açısından','marka/alan adı açısından'],
 ['Sonar + Citations','Sonar + Kaynak Gösterimleri'],
 ['yalnız metin mention ile domain citation birbirinden ayrılır','yalnız metin anılması ile alan adı kaynak gösterimi birbirinden ayrılır'],
 ['Google Search Grounding','Google Search Temellendirme'],
 ['Google Search grounding çıktısındaki','Google Search temellendirme çıktısındaki'],
 ['grounding source URL’leri','temellendirme kaynak URL’leri'],
 ['aynı tarafsız prompt setini','aynı tarafsız istem setini'],
 ['mention/citation değişimini','anılma/kaynak gösterimi değişimini'],
 ['consumer uygulama sonuçlarının','son kullanıcı uygulama sonuçlarının'],
 ['Tracker’ı aç','Takip modülünü aç'],

 ['llms.txt Validator & Kontrol Aracı','llms.txt Doğrulayıcı ve Kontrol Aracı'],
 ['llms.txt v2 describedby ve Markdown alternate keşfi, AI crawler erişimi','llms.txt v2 describedby ve Markdown alternatif keşfi, AI tarayıcı erişimi'],
 ['HTML&HTML llms.txt Validator','HTML&HTML llms.txt Doğrulayıcı'],
 ['LLMS.TXT VALIDATOR / V2','LLMS.TXT DOĞRULAYICI / V2'],
 ['Formatı lint etmek yetmez.','Yalnız biçim denetimi yapmak yetmez.'],
 ['AI crawler erişim sinyallerini','AI tarayıcı erişim sinyallerini'],
 ['Gerçek HTTP link probe','Gerçek HTTP bağlantı sorgusu'],
 ['text/markdown alternate','text/markdown alternatif'],
 ['AI crawler policy','AI tarayıcı politikası'],
 ['Secret alınmaz.','Gizli anahtar alınmaz.'],
 ['HTML&HTML / METHOD','HTML&HTML / YÖNTEM'],
 ['Bir llms.txt validator neyi kanıtlamalı?','Bir llms.txt doğrulayıcı neyi kanıtlamalı?'],
 ['Faydalı bir validator,','Faydalı bir doğrulayıcı,'],
 ['01 / STRUCTURE','01 / YAPI'],
 ['HTTP probe ile','HTTP sorgusuyla'],
 ['metin lint ederek','metin denetimiyle'],
 ['02 / REACHABILITY','02 / ERİŞİLEBİLİRLİK'],
 ['03 / DISCOVERY','03 / KEŞİF'],
 ['Markdown alternate sinyalleri','Markdown alternatif sinyalleri'],
 ['HTML&HTML / COMPARISON','HTML&HTML / KARŞILAŞTIRMA'],
 ['comparison-table yaklaşımı','karşılaştırma tablosu yaklaşımı'],
 ['Basit text lint','Basit metin denetimi'],
 ['Tipik llms.txt checker','Tipik llms.txt kontrol aracı'],
 ['v2 describedby / Markdown discovery','v2 describedby / Markdown keşfi'],
 ['AI crawler policy matrisi','AI tarayıcı politika matrisi'],
 ['Source class + confidence','Kaynak sınıfı + güven düzeyi'],
 ["Rollback/test içeren uygulama mandate'i",'Geri alma/test içeren uygulama talimatı'],
 ['root fix, recovery, prevention, acceptance/regression test ve rollback sözleşmesine','kök düzeltme, kurtarma, önleme, kabul/regresyon testi ve geri alma sözleşmesine'],
 ['ranking, trafik veya AI citation garantisi değildir','sıralama, trafik veya AI kaynak gösterimi garantisi değildir'],
 ["llms.txt proposal'ının",'llms.txt önerisinin'],
 ["private/reserved hedefler, credential içeren URL'ler ve non-standard portlar fail-closed engellenir",'özel/rezerve hedefler, kimlik bilgisi içeren URL’ler ve standart dışı portlar güvenli biçimde reddedilir'],

 ['AI Crawler Checker — ChatGPT, Claude, Perplexity Bot Erişimi','AI Tarayıcı Kontrolü — ChatGPT, Claude, Perplexity Bot Erişimi'],
 ['Web sitenizin AI crawler erişimini','Web sitenizin AI tarayıcı erişimini'],
 ['HTML&HTML AI Crawler Checker','HTML&HTML AI Tarayıcı Kontrolü'],
 ['AI CRAWLER ACCESS CHECKER','AI TARAYICI ERİŞİM KONTROLÜ'],
 ['genel crawl engellerini','genel tarama engellerini'],
 ['Ücretsiz AI crawler erişim kontrolü','Ücretsiz AI tarayıcı erişim kontrolü'],
 ['yalnızca crawl ve AI erişim katmanındaki','yalnızca tarama ve AI erişim katmanındaki'],
 ['Yalnızca public HTTP/HTTPS yüzeyleri. Private/reserved hedefler fail-closed engellenir.','Yalnızca herkese açık HTTP/HTTPS yüzeyleri. Özel/rezerve hedefler güvenli biçimde reddedilir.'],
 ['HTML&HTML / SCOPE','HTML&HTML / KAPSAM'],
 ['crawl edilebilirlik','taranabilirlik'],
 ['01 / CRAWL','01 / TARAMA'],
 ['redirect zinciri','yönlendirme zinciri'],
 ['sitemap ve indexability sinyalleri','site haritası ve indekslenebilirlik sinyalleri'],
 ['02 / BOT POLICY','02 / BOT POLİTİKASI'],
 ['03 / DISCOVERY','03 / KEŞİF'],
 ['discovery işaretleri AI crawler erişiminden','keşif işaretleri AI tarayıcı erişiminden'],
 ['Fix Mandate, robots/header/discovery düzeltmelerini test ve rollback koşullarıyla','Düzeltme Talimatı, robots/başlık/keşif düzeltmelerini test ve geri alma koşullarıyla'],

 ['AI Website Readiness Testi','AI Web Sitesi Hazırlık Testi'],
 ['crawl, teknik SEO, AI/GEO, llms.txt v2, schema, performans, erişilebilirlik, güvenlik, güven, agent readiness, dönüşüm ve link bütünlüğü','tarama, teknik SEO, AI/GEO, llms.txt v2, yapısal veri, performans, erişilebilirlik, güvenlik, güven, ajan hazırlığı, dönüşüm ve bağlantı bütünlüğü'],
 ['HTML&HTML AI Website Readiness Validator','HTML&HTML AI Web Sitesi Hazırlık Doğrulayıcı'],
 ['AI WEBSITE READINESS / 12 ENGINES','AI WEB SİTESİ HAZIRLIĞI / 12 MOTOR'],
 ['12 bağımsız motor public site yüzeyini ölçer; her bulgu severity, confidence, source class ve evidence ile raporlanır','12 bağımsız motor herkese açık site yüzeyini ölçer; her bulgu önem düzeyi, güven düzeyi, kaynak sınıfı ve kanıt ile raporlanır'],
 ['Crawl & Index','Tarama ve İndeksleme'],
 ['Technical SEO','Teknik SEO'],
 ['<span>Schema</span>','<span>Yapısal Veri</span>'],
 ['<span>Security</span>','<span>Güvenlik</span>'],
 ['Agent Ready','Ajan Hazırlığı'],
 ['Ücretsiz 12-motor AI website readiness testi','Ücretsiz 12-motor AI web sitesi hazırlık testi'],
 ['Kanıtlanabilen tüm public sinyaller ölçülür; field data yoksa','Kanıtlanabilen tüm herkese açık sinyaller ölçülür; saha verisi yoksa'],
 ['En fazla 25 public HTML sayfası ve 30 link probe.','En fazla 50 herkese açık HTML sayfası ve 30 bağlantı sorgusu.'],
 ['En fazla 50 public HTML sayfası','En fazla 50 herkese açık HTML sayfası'],
 ['HTML&HTML / MODEL','HTML&HTML / MODEL'],
 ['rastgele bir checklist değildir','rastgele bir kontrol listesi değildir'],
 ['A / ACCESS','A / ERİŞİM'],
 ['Crawl & Index, AI/GEO Access ve Link Integrity','Tarama ve İndeksleme, AI/GEO Erişimi ve Bağlantı Bütünlüğü'],
 ['B / UNDERSTANDING','B / ANLAŞILABİLİRLİK'],
 ['Technical SEO, llms.txt v2, Structured Data ve Agent Readiness','Teknik SEO, llms.txt v2, Yapısal Veri ve Ajan Hazırlığı'],
 ['C / TRUST','C / GÜVEN'],
 ['Security, Content Trust, Accessibility ve Performance Hygiene','Güvenlik, İçerik Güveni, Erişilebilirlik ve Performans Hijyeni'],
 ['D / ACTION','D / EYLEM'],
 ["Conversion ve agent-ready yüzeyler, ziyaretçinin veya agent'ın",'Dönüşüm ve ajan-hazır yüzeyler, ziyaretçinin veya ajanın'],
 ['HTML&HTML / CATEGORY','HTML&HTML / KATEGORİ'],
 ['Tek-purpose validator ile full-site readiness aynı ürün değil.','Tek amaçlı doğrulayıcı ile tam-site hazırlığı aynı ürün değildir.'],
 ['Bir llms.txt checker yalnızca','Bir llms.txt kontrol aracı yalnızca'],
 ['crawl, schema, güvenlik veya link bütünlüğü','tarama, yapısal veri, güvenlik veya bağlantı bütünlüğü'],
 ['Tek-purpose checker','Tek amaçlı kontrol aracı'],
 ['SEO audit','SEO denetimi'],
 ['AI bot policy','AI bot politikası'],
 ['Gerçek link probe','Gerçek bağlantı sorgusu'],
 ['Schema + security + accessibility','Yapısal veri + güvenlik + erişilebilirlik'],
 ['AI coding agent uygulama mandate’i','AI kodlama ajanı uygulama talimatı'],
 ["AI coding agent uygulama mandate'i",'AI kodlama ajanı uygulama talimatı'],
 ['Ücretsiz katman evidence üretir. Ücretli Fix Mandate aynı bulguları root fix, recovery, prevention, acceptance/regression test, rollback ve stop condition yapısına dönüştürür.','Ücretsiz katman kanıt üretir. Ücretli Düzeltme Talimatı aynı bulguları kök düzeltme, kurtarma, önleme, kabul/regresyon testi, geri alma ve durdurma koşulu yapısına dönüştürür.'],

 ['Fix Mandate','Düzeltme Talimatı'],
 ['Full Site Düzeltme Talimatı','Tam Site Düzeltme Talimatı'],
 ['FULL SITE FIX MANDATE','TAM SİTE DÜZELTME TALİMATI'],
 ['public site','herkese açık site'],
 ['public web','herkese açık web'],
 ['public HTML','herkese açık HTML'],
 ['Public HTML','Herkese açık HTML'],
 ['public HTTP/HTTPS','herkese açık HTTP/HTTPS'],
 ['canonical tarama motoru','tek ana tarama motoru'],
 ['canonical scan çekirdeği','tek ana tarama çekirdeği'],
 ['source class','kaynak sınıfı'],
 ['confidence','güven düzeyi'],
 ['audit profile','denetim profili'],
 ['source registry','kaynak kayıt sistemi'],
 ['invariants kurallarını','değişmez kuralları'],
 ['root fix','kök düzeltme'],
 ['rollback','geri alma'],
 ['before/after','önce/sonra'],
 ['retrieval yüzeyleri','bilgi erişim yüzeyleri'],
 ['retrieval ve','bilgi erişimi ve'],
 ['agent hazırlığı','ajan hazırlığı'],
 ['agent-ready','ajan-hazır'],
 ['AI coding agent','AI kodlama ajanı'],
 ['site audit','site denetimi'],
 ['technical audit','teknik denetim'],
 ['AI citation','AI kaynak gösterimi'],
 ['ranking','sıralama'],
 ['consumer uygulama','son kullanıcı uygulaması'],
 ['provider','sağlayıcı'],
 ['Deep Crawl','Derin Tarama']
];

for(const file of files){
  let s=fs.readFileSync(file,'utf8');
  for(const [from,to] of replacements)s=s.split(from).join(to);
  // Localized pages must never bounce through the global root or trailing-slash
  // variants. Keep protocol/third-party URLs untouched.
  s=s.replace(/href="\/"/g,'href="/tr"');
  s=s.replace(/href="(\/(?:tr|en)\/[^"#?]+)\/"/g,'href="$1"');
  fs.writeFileSync(file,s);
}

console.log(`Turkish UI purity pass complete: ${files.length} localized HTML files`);
