import { createHash } from 'node:crypto';
import { unified } from 'unified';
import remarkParse from 'remark-parse';
import { toString } from 'mdast-util-to-string';
import ruleset from './llms-rules-v2.json';

export type LlmsRuleClass='OFFICIAL_SPEC'|'RECOMMENDATION'|'INTERNAL_HEURISTIC';
export type LlmsLevel='blocking'|'warning'|'note'|'pass';
export type LlmsRuleResult={id:string;ok:boolean;level:LlmsLevel;class:LlmsRuleClass;message:string;evidence:string};
export type LlmsLinkResult={url:string;status:number;ok:boolean;redirects:number;finalUrl:string;https:boolean;contentType:string;ttfbMs:number;error?:string};
export type LlmsAudit={
  present:boolean;
  target:string|null;
  candidates:{url:string;status:number;error?:string}[];
  spec:{name:string;version:string;modified:string;source:string;ruleSetId:string};
  engine:{name:string;version:string;parser:string};
  response:{status:number;contentType:string;bytes:number;ttfbMs:number;sha256:string}|null;
  ast:{nodeCount:number;h1:number;h2:number;blockquoteBlocks:number;fileListItems:number};
  rules:LlmsRuleResult[];
  links:LlmsLinkResult[];
  scores:{overall:number;structure:number;links:number;quality:number};
  verdict:'EXCELLENT'|'GOOD'|'NEEDS_IMPROVEMENT'|'CRITICAL'|'NOT_FOUND';
  assumptions:string[];
  warnings:string[];
};

type FetchResult={response:Response;text:string;url:URL;redirects:number;bytes:number;ttfbMs:number};
const UA='HTMLandHTML-LLMS-Engine/2.0 (+https://htmlandhtml.com)';
const SAFETY_MAX_BYTES=1_048_576;
const MAX_REDIRECTS=Number(ruleset.linkProbe.maxRedirects||4);
const TIMEOUT_MS=Number(ruleset.linkProbe.timeoutMs||7000);
const LINK_CONCURRENCY=Number(ruleset.linkProbe.concurrency||8);
const MAX_LINKS=Number(ruleset.linkProbe.maxLinks||250);
const SUCCESS_MIN=Number(ruleset.linkProbe.successMin||200),SUCCESS_MAX=Number(ruleset.linkProbe.successMax||299);
const FALLBACK=new Set<number>((ruleset.linkProbe.headFallbackStatuses||[403,405,501]).map(Number));
const REDIRECTS=new Set([301,302,303,307,308]);

function ipv4(ip:string){const p=ip.split('.');if(p.length!==4||p.some(x=>!/^\d+$/.test(x)||+x>255))return null;return p.map(Number)}
function privateIPv4(ip:string){const p=ipv4(ip);if(!p)return false;return p[0]===0||p[0]===10||p[0]===127||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)||(p[0]===198&&(p[1]===18||p[1]===19))||p[0]>=224}
function privateIPv6(ip:string){const v=ip.toLowerCase();return v==='::'||v==='::1'||v.startsWith('fc')||v.startsWith('fd')||/^fe[89ab]/.test(v)||v.startsWith('::ffff:127.')||v.startsWith('::ffff:10.')||v.startsWith('::ffff:192.168.')}
function normalize(input:string){let s=input.trim();if(!/^https?:\/\//i.test(s))s='https://'+s;const u=new URL(s);if(!['https:','http:'].includes(u.protocol))throw new Error('Only HTTP/HTTPS supported');if(u.username||u.password)throw new Error('Credentials in URL are not allowed');if(u.port&&!['80','443'].includes(u.port))throw new Error('Non-standard ports are not allowed');const h=u.hostname.toLowerCase().replace(/^\[|\]$/g,'');if(h==='localhost'||h.endsWith('.localhost')||h.endsWith('.local')||h.endsWith('.internal')||h.endsWith('.home.arpa')||privateIPv4(h)||privateIPv6(h)||h.includes(':'))throw new Error('Private or local targets are not allowed');u.hash='';return u}
async function resolvePublic(host:string){const h=host.toLowerCase();if(privateIPv4(h)||privateIPv6(h)||h.includes(':'))throw new Error('Private or local target');const headers={accept:'application/dns-json'};const q=encodeURIComponent(h);const settled=await Promise.allSettled([fetch(`https://cloudflare-dns.com/dns-query?name=${q}&type=A`,{headers,signal:AbortSignal.timeout(3500)}),fetch(`https://cloudflare-dns.com/dns-query?name=${q}&type=AAAA`,{headers,signal:AbortSignal.timeout(3500)})]);const answers:string[]=[];for(const x of settled){if(x.status!=='fulfilled'||!x.value.ok)continue;try{const j:any=await x.value.json();answers.push(...(j.Answer||[]).map((a:any)=>String(a.data||'')))}catch{}}if(!answers.length)throw new Error('DNS resolution failed');for(const ip of answers)if(privateIPv4(ip)||privateIPv6(ip))throw new Error('Target resolves to a private or reserved address')}
async function readLimited(r:Response){const declared=Number(r.headers.get('content-length')||0);if(declared>SAFETY_MAX_BYTES)throw new Error('Response exceeds scanner safety size limit');if(!r.body)return '';const reader=r.body.getReader();const chunks:Uint8Array[]=[];let total=0;while(true){const {done,value}=await reader.read();if(done)break;if(value){total+=value.byteLength;if(total>SAFETY_MAX_BYTES){await reader.cancel();throw new Error('Response exceeds scanner safety size limit')}chunks.push(value)}}const out=new Uint8Array(total);let pos=0;for(const c of chunks){out.set(c,pos);pos+=c.byteLength}return new TextDecoder('utf-8',{fatal:false}).decode(out)}
async function safeFetch(input:URL,method:'GET'|'HEAD'='GET'):Promise<FetchResult>{let u=normalize(input.href),redirects=0;while(true){await resolvePublic(u.hostname);const started=performance.now();const r=await fetch(u,{method,redirect:'manual',headers:{'user-agent':UA,'accept':'text/markdown,text/plain,text/html,application/xhtml+xml,*/*'},signal:AbortSignal.timeout(TIMEOUT_MS)});const ttfbMs=Math.round(performance.now()-started);if(REDIRECTS.has(r.status)){if(++redirects>MAX_REDIRECTS)throw new Error('Too many redirects');const loc=r.headers.get('location');if(!loc)throw new Error('Redirect without location');u=normalize(new URL(loc,u).href);continue}const text=method==='HEAD'?'':await readLimited(r.clone());return{response:r,text,url:u,redirects,bytes:new TextEncoder().encode(text).byteLength,ttfbMs}}
}

export function llmsCandidates(input:string){const u=normalize(input);if(/\/llms\.txt$/i.test(u.pathname))return[u.href];let path=u.pathname||'/';if(!path.endsWith('/'))path=path.slice(0,path.lastIndexOf('/')+1)||'/';const seg=path.split('/').filter(Boolean),out:string[]=[];for(let i=seg.length;i>=0;i--){const p=i?`/${seg.slice(0,i).join('/')}/llms.txt`:'/llms.txt',href=new URL(p,u.origin).href;if(!out.includes(href))out.push(href)}return out}

function parse(raw:string){const text=raw.charCodeAt(0)===0xfeff?raw.slice(1):raw;const tree:any=unified().use(remarkParse).parse(text);return{text,tree,bom:raw.charCodeAt(0)===0xfeff}}
function walk(node:any,fn:(n:any,parent:any)=>void,parent:any=null){fn(node,parent);for(const c of node?.children||[])walk(c,fn,node)}
function linksIn(node:any){const out:{label:string,url:string}[]=[];walk(node,(n)=>{if(n?.type==='link'&&typeof n.url==='string')out.push({label:toString(n).trim(),url:n.url.trim()})});return out}
function rr(id:string,ok:boolean,level:LlmsLevel,cls:LlmsRuleClass,message:string,evidence:string):LlmsRuleResult{return{id,ok,level,class:cls,message,evidence}}
function structuralChildren(tree:any){return(tree.children||[]).filter((n:any)=>n.type!=='definition')}
function blockquoteCount(tree:any){return structuralChildren(tree).filter((n:any)=>n.type==='blockquote').length}

export function validateAst(tree:any,raw:string){const rules:LlmsRuleResult[]=[],children=structuralChildren(tree);const headings=children.filter((n:any)=>n.type==='heading');const h1=headings.filter((n:any)=>n.depth===1),h2=headings.filter((n:any)=>n.depth===2);const first=children[0];
if(ruleset.structure.h1ExactlyOne)rules.push(rr('LLM-R001',h1.length===1,'blocking','OFFICIAL_SPEC','Exactly one H1 project/site title is required.',`h1_count=${h1.length}`));
rules.push(rr('LLM-R002',h1.length===1&&Boolean(toString(h1[0]||{}).trim()),'blocking','OFFICIAL_SPEC','The required H1 must be non-empty.',`h1=${toString(h1[0]||{}).trim()||'(missing)'}`));
rules.push(rr('LLM-R003',Boolean(first&&first.type==='heading'&&first.depth===1),'warning','OFFICIAL_SPEC','After an optional BOM, the H1 should be the first structural section.',`first_node=${first?.type||'none'}${first?.depth?` depth=${first.depth}`:''}`));
const bq=blockquoteCount(tree);rules.push(rr('LLM-R004',bq<=1,'warning','OFFICIAL_SPEC','The concise summary is a blockquote section; multiple separated blockquotes do not match the expected sequence.',`blockquote_blocks=${bq}`));
const firstH2=children.findIndex((n:any)=>n.type==='heading'&&n.depth===2);const pre=firstH2<0?children:children.slice(0,firstH2);const preHeadings=pre.filter((n:any)=>n.type==='heading'&&n.depth!==1);rules.push(rr('LLM-R005',preHeadings.length===0,'warning','OFFICIAL_SPEC','Markdown before the H2 file-list sections may contain prose/lists but no additional headings.',`unexpected_heading_count=${preHeadings.length}`));
let activeH2=false,fileListItems=0;const invalidItems:number[]=[],nonLists:string[]=[];for(let i=0;i<children.length;i++){const n=children[i];if(n.type==='heading'&&n.depth===2){activeH2=true;continue}if(n.type==='heading'){if(activeH2)nonLists.push(`${n.type}:${n.depth}`);continue}if(!activeH2)continue;if(n.type==='list'){for(const li of n.children||[]){fileListItems++;if(!linksIn(li).length)invalidItems.push(fileListItems)}continue}nonLists.push(n.type)}
rules.push(rr('LLM-R006',invalidItems.length===0,'blocking','OFFICIAL_SPEC','Each file-list item under an H2 must contain a Markdown hyperlink.',`invalid_file_list_items=${invalidItems.join(',')||'none'}`));
rules.push(rr('LLM-R007',nonLists.length===0,'warning','OFFICIAL_SPEC','H2 sections are file-list sections and should resolve to Markdown lists rather than free prose or nested headings.',`non_list_nodes=${nonLists.join(',')||'none'}`));
const allLinks:{label:string,url:string}[]=[];let underH2=false;for(const n of children){if(n.type==='heading'&&n.depth===2){underH2=true;continue}if(underH2&&n.type==='list')allLinks.push(...linksIn(n))}
const unique=new Set(allLinks.map(x=>x.url));rules.push(rr('LLM-R009',unique.size===allLinks.length,'warning','RECOMMENDATION','Avoid duplicate resource URLs in file lists.',`unique=${unique.size} total=${allLinks.length}`));
rules.push(rr('LLM-R010',bq>0,'note','RECOMMENDATION','A concise blockquote summary is recommended for fast orientation but is not required in v2.',`summary=${bq>0?'present':'missing'}`));
const optional=h2.some((n:any)=>toString(n).trim().toLowerCase()==='optional');rules.push(rr('LLM-R011',true,'pass','RECOMMENDATION','Optional is a useful secondary-content convention, but v2 no longer gives it mechanical omission semantics.',`optional_section=${optional?'present':'absent'}`));
const bytes=new TextEncoder().encode(raw).byteLength;rules.push(rr('LLM-R012',true,'pass','INTERNAL_HEURISTIC','File size is telemetry; v2 defines no fixed byte limit.',`bytes=${bytes} hard_spec_limit=${String(ruleset.delivery.hardByteLimit)}`));
const frontmatter=/^\uFEFF?---\s*\n/.test(raw);rules.push(rr('LLM-R013',true,'pass','INTERNAL_HEURISTIC','Frontmatter is observed but not called a spec violation without a normative prohibition.',`frontmatter=${frontmatter}`));
return{rules,fileListItems,links:allLinks,stats:{nodeCount:children.length,h1:h1.length,h2:h2.length,blockquoteBlocks:bq}}}

async function probeOne(raw:string,base:URL):Promise<LlmsLinkResult>{let u:URL;try{u=normalize(new URL(raw,base).href)}catch(e:any){return{url:raw,status:0,ok:false,redirects:0,finalUrl:raw,https:false,contentType:'',ttfbMs:0,error:e?.message||'invalid URL'}}try{let x=await safeFetch(u,'HEAD');if(FALLBACK.has(x.response.status))x=await safeFetch(u,'GET');return{url:raw,status:x.response.status,ok:x.response.status>=SUCCESS_MIN&&x.response.status<=SUCCESS_MAX,redirects:x.redirects,finalUrl:x.url.href,https:x.url.protocol==='https:',contentType:(x.response.headers.get('content-type')||'').split(';')[0].trim().toLowerCase(),ttfbMs:x.ttfbMs}}catch(e:any){return{url:raw,status:0,ok:false,redirects:0,finalUrl:u.href,https:u.protocol==='https:',contentType:'',ttfbMs:0,error:e?.message||'probe failed'}}}
async function mapLimit<T,R>(items:T[],limit:number,fn:(x:T)=>Promise<R>){const out=new Array<R>(items.length);let cursor=0;async function worker(){while(true){const i=cursor++;if(i>=items.length)return;out[i]=await fn(items[i])}}await Promise.all(Array.from({length:Math.min(limit,items.length)},()=>worker()));return out}
function weightedPass(rules:LlmsRuleResult[],classes:LlmsRuleClass[]){const selected=rules.filter(r=>classes.includes(r.class)&&r.level!=='pass');if(!selected.length)return 100;let den=0,num=0;for(const r of selected){const w=r.level==='blocking'?4:r.level==='warning'?2:1;den+=w;if(r.ok)num+=w}return den?Math.round(num/den*100):100}
function verdict(score:number,found:boolean){if(!found)return'NOT_FOUND' as const;for(const x of ruleset.scoring.verdicts||[]){if(score>=Number(x.min))return x.label as LlmsAudit['verdict']}return'CRITICAL' as const}

export async function auditLlms(input:string):Promise<LlmsAudit>{const candidates=llmsCandidates(input),candidateLog:LlmsAudit['candidates']=[];let chosen:FetchResult|null=null;for(const c of candidates){try{const x=await safeFetch(new URL(c),'GET');candidateLog.push({url:c,status:x.response.status});if(x.response.status>=SUCCESS_MIN&&x.response.status<=SUCCESS_MAX){chosen=x;break}}catch(e:any){candidateLog.push({url:c,status:0,error:e?.message||'fetch failed'})}}
const spec={name:ruleset.spec.name,version:ruleset.spec.version,modified:ruleset.spec.modified,source:ruleset.spec.source,ruleSetId:ruleset.ruleSetId};const engine={name:'HTML&HTML Formal llms.txt Engine',version:'2.0.0',parser:'unified/remark CommonMark AST'};
if(!chosen)return{present:false,target:null,candidates:candidateLog,spec,engine,response:null,ast:{nodeCount:0,h1:0,h2:0,blockquoteBlocks:0,fileListItems:0},rules:[],links:[],scores:{overall:0,structure:0,links:0,quality:0},verdict:'NOT_FOUND',assumptions:['llms.txt is a proposal, not a Google/Search ranking requirement.','Candidate resolution follows v2 path coverage and prefers the most-specific applicable llms.txt.'],warnings:['No reachable llms.txt candidate was found. This is readiness telemetry, not a search-ranking failure.']};
const parsed=parse(chosen.text),v=validateAst(parsed.tree,chosen.text);const unique=[...new Set(v.links.map(x=>x.url))].slice(0,MAX_LINKS);const links=await mapLimit(unique,LINK_CONCURRENCY,u=>probeOne(u,chosen!.url));const reachable=links.filter(x=>x.ok).length,redirectFree=links.filter(x=>x.ok&&x.redirects===0).length,llmFriendly=links.filter(x=>x.ok&&(ruleset.delivery.preferredContentTypes.includes(x.contentType)||/\.md(?:$|\?)/i.test(x.finalUrl))).length;
for(const l of links){if(!l.ok)v.rules.push(rr(`LLM-LINK-${createHash('sha1').update(l.url).digest('hex').slice(0,10)}`,false,'blocking','OFFICIAL_SPEC','A file-list resource is not reachable with a successful 2xx response.',`${l.status||'ERR'} ${l.url}${l.error?` (${l.error})`:''}`));else{if(l.redirects)v.rules.push(rr(`LLM-REDIRECT-${createHash('sha1').update(l.url).digest('hex').slice(0,10)}`,false,'warning','RECOMMENDATION','A file-list resource redirects; direct final destinations are more deterministic for agents.',`${l.url} -> ${l.finalUrl} hops=${l.redirects}`));if(!l.https)v.rules.push(rr(`LLM-HTTPS-${createHash('sha1').update(l.url).digest('hex').slice(0,10)}`,false,'warning','RECOMMENDATION','Prefer HTTPS resource URLs.',`${l.url} -> ${l.finalUrl}`))}}
const structure=weightedPass(v.rules.filter(r=>/^LLM-R00[1-7]$/.test(r.id)),['OFFICIAL_SPEC']);const linkScore=links.length?Math.round((reachable/links.length)*85+(redirectFree/links.length)*15):100;const baseQuality=weightedPass(v.rules,['RECOMMENDATION']);const friendly=links.length?Math.round(llmFriendly/links.length*100):100;const quality=Math.round(baseQuality*.65+friendly*.35);const sw=ruleset.scoring.weights;let overall=Math.round((structure*Number(sw.structure)+linkScore*Number(sw.links)+quality*Number(sw.quality))/100);if(v.rules.some(r=>r.class==='OFFICIAL_SPEC'&&r.level==='blocking'&&!r.ok))overall=Math.min(overall,Number(ruleset.scoring.blockingSpecFailureCap||49));
const contentType=(chosen.response.headers.get('content-type')||'').toLowerCase(),warnings:string[]=[];if(contentType&&!ruleset.delivery.preferredContentTypes.some((x:string)=>contentType.includes(x)))warnings.push(`Content-Type is ${contentType}; Markdown/text delivery is safer for deterministic consumers.`);if(chosen.redirects)warnings.push(`llms.txt discovery followed ${chosen.redirects} redirect(s).`);if(v.links.length>MAX_LINKS)warnings.push(`Only the first ${MAX_LINKS} unique links were probed by the bounded public validator.`);const hash=createHash('sha256').update(Buffer.from(chosen.text,'utf8')).digest('hex');return{present:true,target:chosen.url.href,candidates:candidateLog,spec,engine,response:{status:chosen.response.status,contentType:contentType||'',bytes:chosen.bytes,ttfbMs:chosen.ttfbMs,sha256:hash},ast:{...v.stats,fileListItems:v.fileListItems},rules:v.rules,links,scores:{overall,structure,links:linkScore,quality},verdict:verdict(overall,true),assumptions:['Only H1 is treated as the required v2 section; the blockquote summary is recommended, not required.','The Optional section has no mechanical omission semantics in v2.','Link success means a reachable 2xx response from this validator runtime; it does not prove every AI vendor can traverse the same CDN/WAF path.','The llms.txt score weights are an explicit HTML&HTML INTERNAL_HEURISTIC loaded from the versioned rule set, not part of the proposal.'],warnings}}
