import { createHash } from 'node:crypto';

export type LlmsRuleClass='OFFICIAL_SPEC'|'RECOMMENDATION'|'INTERNAL_HEURISTIC';
export type LlmsLevel='blocking'|'warning'|'note'|'pass';
export type LlmsNode={kind:'h1'|'h2'|'heading'|'blockquote'|'list-item'|'paragraph'|'blank'|'fence';line:number,text:string,level?:number,links?:{label:string,url:string}[]};
export type LlmsRuleResult={id:string;ok:boolean;level:LlmsLevel,class:LlmsRuleClass;message:string;evidence:string};
export type LlmsLinkResult={url:string,status:number,ok:boolean,redirects:number,finalUrl:string,https:boolean,contentType:string,ttfbMs:number,error?:string};
export type LlmsAudit={
  present:boolean;
  target:string|null;
  candidates:{url:string,status:number,error?:string}[];
  spec:{name:string;version:string;modified:string;source:string};
  engine:{name:string;version:string};
  response:{status:number;contentType:string;bytes:number;ttfbMs:number;sha256:string}|null;
  ast:{nodeCount:number,h1:number,h2:number,blockquoteBlocks:number,fileListItems:number};
  rules:LlmsRuleResult[];
  links:LlmsLinkResult[];
  scores:{overall:number;structure:number;links:number;quality:number};
  verdict:'EXCELLENT'|'GOOD'|'NEEDS_IMPROVEMENT'|'CRITICAL'|'NOT_FOUND';
  assumptions:string[];
  warnings:string[];
};

type FetchResult={response:Response,text:string,url:URL,redirects:number,bytes:number,ttfbMs:number};
const UA='HTMLandHTML-LLMS-Engine/1.0 (+https://htmlandhtml.com)';
const MAX_BYTES=1_048_576,MAX_REDIRECTS=4,TIMEOUT_MS=7000,LINK_CONCURRENCY=8,MAX_LINKS=250;
const REDIRECTS=new Set([301,302,303,307,308]);

function ipv4(ip:string){const p=ip.split('.');if(p.length!==4||p.some(x=>!/^\d+$/.test(x)||+x>255))return null;return p.map(Number)}
function privateIPv4(ip:string){const p=ipv4(ip);if(!p)return false;return p[0]===0||p[0]===10||p[0]===127||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)||(p[0]===198&&(p[1]===18||p[1]===19))||p[0]>=224}
function privateIPv6(ip:string){const v=ip.toLowerCase();return v==='::'||v==='::1'||v.startsWith('fc')||v.startsWith('fd')||/^fe[89ab]/.test(v)||v.startsWith('::ffff:127.')||v.startsWith('::ffff:10.')||v.startsWith('::ffff:192.168.')}
function normalize(input:string){let s=input.trim();if(!/^https?:\/\//i.test(s))s='https://'+s;const u=new URL(s);if(!['https:','http:'].includes(u.protocol))throw new Error('Only HTTP/HTTPS supported');if(u.username||u.password)throw new Error('Credentials in URL are not allowed');if(u.port&&!['80','443'].includes(u.port))throw new Error('Non-standard ports are not allowed');const h=u.hostname.toLowerCase().replace(/^\[|\]$/g,'');if(h==='localhost'||h.endsWith('.localhost')||h.endsWith('.local')||h.endsWith('.internal')||h.endsWith('.home.arpa')||privateIPv4(h)||privateIPv6(h)||h.includes(':'))throw new Error('Private or local targets are not allowed');u.hash='';return u}
async function resolvePublic(host:string){const h=host.toLowerCase();if(privateIPv4(h)||privateIPv6(h)||h.includes(':'))throw new Error('Private or local target');const headers={accept:'application/dns-json'};const q=encodeURIComponent(h);const settled=await Promise.allSettled([fetch(`https://cloudflare-dns.com/dns-query?name=${q}&type=A`,{headers,signal:AbortSignal.timeout(3500)}),fetch(`https://cloudflare-dns.com/dns-query?name=${q}&type=AAAA`,{headers,signal:AbortSignal.timeout(3500)})]);const answers:string[]=[];for(const x of settled){if(x.status!=='fulfilled'||!x.value.ok)continue;try{const j:any=await x.value.json();answers.push(...(j.Answer||[]).map((a:any)=>String(a.data||'')))}catch{}}if(!answers.length)throw new Error('DNS resolution failed');for(const ip of answers)if(privateIPv4(ip)||privateIPv6(ip))throw new Error('Target resolves to a private or reserved address')}
async function readLimited(r:Response){const declared=Number(r.headers.get('content-length')||0);if(declared>MAX_BYTES)throw new Error('Response exceeds size limit');if(!r.body)return '';const reader=r.body.getReader();const chunks:Uint8Array[]=[];let total=0;while(true){const {done,value}=await reader.read();if(done)break;if(value){total+=value.byteLength;if(total>MAX_BYTES){await reader.cancel();throw new Error('Response exceeds size limit')}chunks.push(value)}}const out=new Uint8Array(total);let pos=0;for(const c of chunks){out.set(c,pos);pos+=c.byteLength}return new TextDecoder('utf-8',{fatal:false}).decode(out)}
async function safeFetch(input:URL,method:'GET'|'HEAD'='GET'):Promise<FetchResult>{let u=normalize(input.href),redirects=0;const started=Date.now();while(true){await resolvePublic(u.hostname);const r=await fetch(u,{method,redirect:'manual',headers:{'user-agent':UA,'accept':'text/markdown,text/plain,text/html,application/xhtml+xml,*/*'},signal:AbortSignal.timeout(TIMEOUT_MS)});if(REDIRECTS.has(r.status)){if(++redirects>MAX_REDIRECTS)throw new Error('Too many redirects');const loc=r.headers.get('location');if(!loc)throw new Error('Redirect without location');u=normalize(new URL(loc,u).href);continue}const text=method==='HEAD'?'':await readLimited(r.clone());return{response:r,text,url:u,redirects,bytes:new TextEncoder().encode(text).byteLength,ttfbMs:Date.now()-started}}
}

export function llmsCandidates(input:string){const u=normalize(input);if(/\/llms\.txt$/i.test(u.pathname))return [u.href];let path=u.pathname||'/';if(!path.endsWith('/'))path=path.slice(0,path.lastIndexOf('/')+1)||'/';const seg=path.split('/').filter(Boolean);const out:string[]=[];for(let i=seg.length;i>=0;i--){const p=i?`/${seg.slice(0,i).join('/')}/llms.txt`:'/llms.txt';const x=new URL(p,u.origin).href;if(!out.includes(x))out.push(x)}return out}

function extractLinks(text:string){const links:{label:string,url:string}[]=[];const re=/\[([^\]]+)\]\(([^)\s]+)(?:\s+["'][^"']*["'])?\)/g;let m;while((m=re.exec(text)))links.push({label:m[1].trim(),url:m[2].trim()});return links}
export function parseLlms(raw:string){let text=raw;if(text.charCodeAt(0)===0xfeff)text=text.slice(1);const lines=text.replace(/\r\n?/g,'\n').split('\n');const nodes:LlmsNode[]=[];let inFence=false;for(let i=0;i<lines.length;i++){const line=lines[i],trim=line.trim();if(/^```|^~~~/.test(trim)){inFence=!inFence;nodes.push({kind:'fence',line:i+1,text:line});continue}if(inFence){nodes.push({kind:'paragraph',line:i+1,text:line});continue}if(!trim){nodes.push({kind:'blank',line:i+1,text:''});continue}let m;if((m=line.match(/^#\s+(.+)$/))){nodes.push({kind:'h1',line:i+1,text:m[1].trim(),level:1});continue}if((m=line.match(/^##\s+(.+)$/))){nodes.push({kind:'h2',line:i+1,text:m[1].trim(),level:2});continue}if((m=line.match(/^(#{3,6})\s+(.+)$/))){nodes.push({kind:'heading',line:i+1,text:m[2].trim(),level:m[1].length});continue}if(/^>\s?/.test(line)){nodes.push({kind:'blockquote',line:i+1,text:line.replace(/^>\s?/, '').trim()});continue}if((m=line.match(/^\s*(?:[-+*]|\d+\.)\s+(.+)$/))){nodes.push({kind:'list-item',line:i+1,text:m[1].trim(),links:extractLinks(m[1])});continue}nodes.push({kind:'paragraph',line:i+1,text:trim,links:extractLinks(trim)})}
return{bom:raw.charCodeAt(0)===0xfeff,nodes,text}}

function blockquoteBlocks(nodes:LlmsNode[]){let count=0,active=false;for(const n of nodes){if(n.kind==='blockquote'){if(!active)count++;active=true}else if(n.kind!=='blank')active=false}return count}
function rr(id:string,ok:boolean,level:LlmsLevel,cls:LlmsRuleClass,message:string,evidence:string):LlmsRuleResult{return{id,ok,level,class:cls,message,evidence}}
export function validateAst(nodes:LlmsNode[],raw:string){const rules:LlmsRuleResult[]=[];const meaningful=nodes.filter(n=>n.kind!=='blank');const h1=nodes.filter(n=>n.kind==='h1');const h2=nodes.filter(n=>n.kind==='h2');const bq=blockquoteBlocks(nodes);
rules.push(rr('LLM-R001',h1.length===1,'blocking','OFFICIAL_SPEC','Exactly one H1 project/site title is required.',`h1_count=${h1.length}`));
rules.push(rr('LLM-R002',h1.length===1&&Boolean(h1[0]?.text.trim()),'blocking','OFFICIAL_SPEC','The required H1 must be non-empty.',`h1=${h1[0]?.text||'(missing)'}`));
const first=meaningful[0];rules.push(rr('LLM-R003',Boolean(first&&first.kind==='h1'),'warning','OFFICIAL_SPEC','After an optional BOM, the H1 should be the first section.',`first_node=${first?.kind||'none'} line=${first?.line||0}`));
rules.push(rr('LLM-R004',bq<=1,'warning','OFFICIAL_SPEC','The short project summary is represented as a blockquote section; multiple separated blockquote sections break the expected sequence.',`blockquote_blocks=${bq}`));
const firstH2=nodes.findIndex(n=>n.kind==='h2');const beforeH2=firstH2<0?nodes:nodes.slice(0,firstH2);const extraHeading=beforeH2.filter(n=>n.kind==='heading'||n.kind==='h2');rules.push(rr('LLM-R005',extraHeading.length===0,'warning','OFFICIAL_SPEC','Pre-link prose may contain Markdown content but no headings before H2 file-list sections.',`unexpected_headings=${extraHeading.map(n=>`L${n.line}`).join(',')||'none'}`));
let section:string|null=null;const badItems:number[]=[];const nonListAfterH2:number[]=[];let fileListItems=0;for(const n of nodes){if(n.kind==='h2'){section=n.text;continue}if(!section||n.kind==='blank')continue;if(n.kind==='list-item'){fileListItems++;if(!n.links?.length)badItems.push(n.line);continue}if(n.kind==='paragraph'||n.kind==='heading'||n.kind==='blockquote')nonListAfterH2.push(n.line)}
rules.push(rr('LLM-R006',badItems.length===0,'blocking','OFFICIAL_SPEC','Each file-list item under an H2 must contain a Markdown hyperlink.',`invalid_item_lines=${badItems.join(',')||'none'}`));
rules.push(rr('LLM-R007',nonListAfterH2.length===0,'warning','OFFICIAL_SPEC','H2 sections are file-list sections and should resolve to Markdown list items rather than free prose.',`non_list_lines=${nonListAfterH2.join(',')||'none'}`));
const allLinks=nodes.flatMap(n=>n.kind==='list-item'?(n.links||[]):[]);const https=allLinks.filter(x=>{try{return new URL(x.url).protocol==='https:'}catch{return false}}).length;rules.push(rr('LLM-R008',!allLinks.length||https===allLinks.length,'warning','RECOMMENDATION','Use HTTPS for linked resources.',`https_links=${https}/${allLinks.length}`));
const urls=allLinks.map(x=>x.url);rules.push(rr('LLM-R009',new Set(urls).size===urls.length,'warning','RECOMMENDATION','Avoid duplicate resource URLs.',`unique=${new Set(urls).size} total=${urls.length}`));
const bqNode=nodes.find(n=>n.kind==='blockquote');rules.push(rr('LLM-R010',Boolean(bqNode),'note','RECOMMENDATION','A concise blockquote summary is recommended for fast orientation but is not required in v2.',`summary=${bqNode?'present':'missing'}`));
const optional=h2.find(n=>n.text.trim().toLowerCase()==='optional');rules.push(rr('LLM-R011',true,'pass','RECOMMENDATION','An Optional section is a convention for secondary links only; v2 gives it no mechanical semantics.',`optional_section=${optional?'present':'absent'}`));
const bytes=new TextEncoder().encode(raw).byteLength;rules.push(rr('LLM-R012',true,'pass','INTERNAL_HEURISTIC','Context efficiency is reported as telemetry; v2 defines no 10KB hard limit.',`bytes=${bytes}`));
const frontmatter=/^\uFEFF?---\s*\n/.test(raw);rules.push(rr('LLM-R013',true,'pass','INTERNAL_HEURISTIC','YAML/frontmatter presence is observed but not treated as a spec violation because v2 does not explicitly prohibit it.',`frontmatter=${frontmatter}`));
return{rules,fileListItems,links:allLinks}}

async function probeOne(raw:string,base:URL):Promise<LlmsLinkResult>{let u:URL;try{u=normalize(new URL(raw,base).href)}catch(e:any){return{url:raw,status:0,ok:false,redirects:0,finalUrl:raw,https:false,contentType:'',ttfbMs:0,error:e?.message||'invalid URL'}}try{let x=await safeFetch(u,'HEAD');if([403,405,501].includes(x.response.status))x=await safeFetch(u,'GET');return{url:raw,status:x.response.status,ok:x.response.status>=200&&x.response.status<300,redirects:x.redirects,finalUrl:x.url.href,https:x.url.protocol==='https:',contentType:(x.response.headers.get('content-type')||'').split(';')[0].trim().toLowerCase(),ttfbMs:x.ttfbMs}}catch(e:any){return{url:raw,status:0,ok:false,redirects:0,finalUrl:u.href,https:u.protocol==='https:',contentType:'',ttfbMs:0,error:e?.message||'probe failed'}}}
async function mapLimit<T,R>(items:T[],limit:number,fn:(x:T)=>Promise<R>){const out=new Array<R>(items.length);let cursor=0;async function worker(){while(true){const i=cursor++;if(i>=items.length)return;out[i]=await fn(items[i])}}await Promise.all(Array.from({length:Math.min(limit,items.length)},()=>worker()));return out}
function weightedPass(rules:LlmsRuleResult[],classes:LlmsRuleClass[]){const selected=rules.filter(r=>classes.includes(r.class)&&r.level!=='pass');if(!selected.length)return 100;let den=0,num=0;for(const r of selected){const w=r.level==='blocking'?4:r.level==='warning'?2:1;den+=w;if(r.ok)num+=w}return den?Math.round(num/den*100):100}
function verdict(score:number,found:boolean){if(!found)return'NOT_FOUND' as const;if(score>=90)return'EXCELLENT' as const;if(score>=70)return'GOOD' as const;if(score>=50)return'NEEDS_IMPROVEMENT' as const;return'CRITICAL' as const}

export async function auditLlms(input:string):Promise<LlmsAudit>{const candidates=llmsCandidates(input),candidateLog:LlmsAudit['candidates']=[];let chosen:FetchResult|null=null;for(const c of candidates){try{const x=await safeFetch(new URL(c),'GET');candidateLog.push({url:c,status:x.response.status});if(x.response.status>=200&&x.response.status<300){chosen=x;break}}catch(e:any){candidateLog.push({url:c,status:0,error:e?.message||'fetch failed'})}}
const spec={name:'llms.txt',version:'v2',modified:'2026-08-10',source:'https://llmstxt.org/'};const engine={name:'HTML&HTML Formal llms.txt Engine',version:'1.0.0'};if(!chosen)return{present:false,target:null,candidates:candidateLog,spec,engine,response:null,ast:{nodeCount:0,h1:0,h2:0,blockquoteBlocks:0,fileListItems:0},rules:[],links:[],scores:{overall:0,structure:0,links:0,quality:0},verdict:'NOT_FOUND',assumptions:['llms.txt is a proposal, not a Google/Search ranking requirement.','Candidate resolution follows v2 path coverage: the most specific applicable llms.txt is preferred.'],warnings:['No reachable llms.txt candidate was found. This is reported as readiness telemetry, not as a search-ranking failure.']};
const parsed=parseLlms(chosen.text);const v=validateAst(parsed.nodes,chosen.text);const unique=[...new Set(v.links.map(x=>x.url))].slice(0,MAX_LINKS);const links=await mapLimit(unique,LINK_CONCURRENCY,u=>probeOne(u,chosen!.url));const reachable=links.filter(x=>x.ok).length;const redirectFree=links.filter(x=>x.ok&&x.redirects===0).length;const llmFriendly=links.filter(x=>x.ok&&(x.contentType==='text/markdown'||x.contentType==='text/plain'||/\.md(?:$|\?)/i.test(x.finalUrl))).length;
for(const l of links){if(!l.ok)v.rules.push(rr(`LLM-LINK-${createHash('sha1').update(l.url).digest('hex').slice(0,10)}`,false,'blocking','OFFICIAL_SPEC','A file-list resource is not reachable with a successful 2xx response.',`${l.status||'ERR'} ${l.url}${l.error?` (${l.error})`:''}`));else if(l.redirects)v.rules.push(rr(`LLM-REDIRECT-${createHash('sha1').update(l.url).digest('hex').slice(0,10)}`,false,'warning','RECOMMENDATION','A file-list resource redirects; direct canonical destinations are more deterministic for agents.',`${l.url} -> ${l.finalUrl} hops=${l.redirects}`))}
const structure=weightedPass(v.rules.filter(r=>/^LLM-R00[1-7]$/.test(r.id)),['OFFICIAL_SPEC']);const linkScore=links.length?Math.round((reachable/links.length)*85+(redirectFree/links.length)*15):100;const baseQuality=weightedPass(v.rules,['RECOMMENDATION']);const friendly=links.length?Math.round(llmFriendly/links.length*100):100;const quality=Math.round(baseQuality*.65+friendly*.35);let overall=Math.round(structure*.35+linkScore*.40+quality*.25);if(v.rules.some(r=>r.class==='OFFICIAL_SPEC'&&r.level==='blocking'&&!r.ok))overall=Math.min(overall,49);const contentType=(chosen.response.headers.get('content-type')||'').toLowerCase();const mimeOk=/text\/(plain|markdown|x-markdown)/.test(contentType);const warnings:string[]=[];if(!mimeOk)warnings.push(`Content-Type is ${contentType||'(missing)'}; Markdown/text delivery is safer for deterministic consumers.`);if(chosen.redirects)warnings.push(`llms.txt discovery followed ${chosen.redirects} redirect(s).`);if(unique.length>MAX_LINKS)warnings.push(`Only the first ${MAX_LINKS} unique links were probed.`);const hash=createHash('sha256').update(Buffer.from(chosen.text,'utf8')).digest('hex');return{present:true,target:chosen.url.href,candidates:candidateLog,spec,engine,response:{status:chosen.response.status,contentType:contentType||'',bytes:chosen.bytes,ttfbMs:chosen.ttfbMs,sha256:hash},ast:{nodeCount:parsed.nodes.length,h1:parsed.nodes.filter(n=>n.kind==='h1').length,h2:parsed.nodes.filter(n=>n.kind==='h2').length,blockquoteBlocks:blockquoteBlocks(parsed.nodes),fileListItems:v.fileListItems},rules:v.rules,links,scores:{overall,structure,links:linkScore,quality},verdict:verdict(overall,true),assumptions:['Only H1 is treated as the required v2 section; the blockquote summary is recommended, not required.','The Optional section is conventional secondary content and has no mechanical omission semantics in v2.','Link success means a reachable 2xx response from this validator runtime; it does not guarantee every AI vendor can traverse the same CDN/WAF path.','The 35/40/25 score mix is an HTML&HTML internal heuristic and is not part of the llms.txt proposal.'],warnings}}
