import type { Finding, ScanResult, SourceClass } from './scan-engine';

export const OPPORTUNITY_VERSION='1.0.0' as const;
export const OPPORTUNITY_SIGNAL_COUNT=12 as const;
export type OpportunityKey=
  |'query_fanout_coverage'
  |'non_commodity_evidence'
  |'citation_source_readiness'
  |'answer_unit_architecture'
  |'entity_resolution_depth'
  |'retrieval_surface_coherence'
  |'discovery_graph_coherence'
  |'commercial_path_clarity'
  |'trust_accountability'
  |'freshness_provenance'
  |'multimodal_accessibility'
  |'observability_gap';
export type OpportunityStatus='STRONG'|'OPPORTUNITY'|'BLOCKED'|'NOT_MEASURED'|'REQUIRES_CONTEXT';
export type CommercialRelevance='LOW'|'MEDIUM'|'HIGH'|'CRITICAL';
export type Lens='SEO'|'GEO'|'AEO'|'LLMO'|'AAO'|'RAG'|'E-E-A-T';

export interface OpportunitySignal {
  key:OpportunityKey;
  labelTr:string;
  labelEn:string;
  status:OpportunityStatus;
  confidence:number;
  sourceClass:SourceClass;
  commercialRelevance:CommercialRelevance;
  lenses:Lens[];
  evidence:string[];
  affectedUrls:string[];
  diagnosisTr:string;
  diagnosisEn:string;
  boundaryTr:string;
  boundaryEn:string;
}
export interface OpportunityPriority {
  rank:number;
  key:OpportunityKey;
  status:OpportunityStatus;
  commercialRelevance:CommercialRelevance;
  confidence:number;
}
export interface OpportunityReport {
  version:typeof OPPORTUNITY_VERSION;
  classification:'NON_SCORING_ENTERPRISE_OPPORTUNITY_LAYER';
  canonicalScoreUnchanged:true;
  domain:string;
  scanId:string;
  signals:OpportunitySignal[];
  topOpportunities:OpportunityPriority[];
  measuredSignals:number;
  contextRequired:number;
  boundaries:string[];
}
export type Owner='DEVELOPER'|'SEO'|'CONTENT'|'BUSINESS_OWNER'|'PR_AUTHORITY'|'ANALYTICS';
export interface OpportunityAction {
  key:OpportunityKey;
  owner:Owner[];
  dependencies:OpportunityKey[];
  blastRadius:'URL'|'SECTION'|'SITE_WIDE'|'EXTERNAL_DATA';
  changeClass:'CONTENT'|'TECHNICAL'|'ENTITY'|'DISCOVERY'|'CONVERSION'|'MEASUREMENT'|'MULTIMODAL';
  implementationOrder:number;
  implementationState:'ACTIONABLE'|'VERIFY_FIRST'|'CONTEXT_REQUIRED';
  plan:string[];
  acceptanceTests:string[];
  regressionTests:string[];
  rollback:string[];
  stopConditions:string[];
}

const rank:Record<CommercialRelevance,number>={LOW:1,MEDIUM:2,HIGH:3,CRITICAL:4};
const uniq=<T>(xs:T[])=>[...new Set(xs)];
const byCat=(scan:ScanResult,c:string)=>scan.findings.filter(f=>f.category===c);
const pref=(scan:ScanResult,p:string)=>scan.findings.filter(f=>f.id.startsWith(p));
const affected=(fs:Finding[])=>uniq(fs.map(x=>x.url).filter(Boolean) as string[]).slice(0,20);
const ev=(fs:Finding[],fallback:string)=>fs.length?uniq(fs.map(x=>`${x.id}: ${x.evidence}`)).slice(0,10):[fallback];
const scoreStatus=(bad:number,critical=false):OpportunityStatus=>bad===0?'STRONG':critical||bad>=3?'BLOCKED':'OPPORTUNITY';

function make(x:OpportunitySignal){return x}

export function generateOpportunityReport(scan:ScanResult):OpportunityReport{
  const pages=Number(scan.summary?.pagesScanned||0);
  const schemaTypes=(scan.summary?.schemaTypes||[]) as string[];
  const technical=byCat(scan,'technical'), trust=byCat(scan,'trust'), links=byCat(scan,'links'), llms=byCat(scan,'llms'), agent=byCat(scan,'agent'), conversion=byCat(scan,'conversion'), a11y=byCat(scan,'accessibility');
  const intent=[...pref(scan,'TECH-DUPTITLE'),...pref(scan,'TECH-H1'),...pref(scan,'TECH-CANON')];
  const evidenceTypes=['Dataset','DataCatalog','SoftwareApplication','WebApplication','HowTo','Product','Article'].filter(x=>schemaTypes.includes(x));
  const entityTypes=['Organization','Person','WebSite','WebPage','Product','Service','SoftwareApplication'].filter(x=>schemaTypes.includes(x));
  const discovery=[...byCat(scan,'crawl'),...links,...pref(scan,'TECH-CANON'),...llms];
  const answer=[...pref(scan,'TECH-H1'),...pref(scan,'TECH-META'),...pref(scan,'TECH-TITLE')];
  const signals:OpportunitySignal[]=[
    make({key:'query_fanout_coverage',labelTr:'Query Fan-out ve Alt-Soru Kapsaması',labelEn:'Query Fan-out & Subtopic Coverage',status:scoreStatus(intent.length),confidence:0.78,sourceClass:'INTERNAL_HEURISTIC',commercialRelevance:'HIGH',lenses:['SEO','GEO','AEO','LLMO'],evidence:ev(intent,`${pages} public page scanned; no exact duplicate-title/canonical collision measured inside the crawl boundary.`),affectedUrls:affected(intent),diagnosisTr:'AI arama sistemlerinin bir sorguyu alt sorgulara ayırabildiği ortamda sayfaların niyet ayrışması ve konu mimarisi kritik bir fırsat katmanıdır.',diagnosisEn:'Where AI search can fan a query out into subqueries, intent separation and topic architecture become a material opportunity layer.',boundaryTr:'Gerçek sorgu evreni Search Console veya harici query verisi olmadan ölçülemez; bu sinyal public site mimarisini değerlendirir.',boundaryEn:'The real query universe cannot be measured without Search Console or external query data; this signal evaluates public site architecture.'}),
    make({key:'non_commodity_evidence',labelTr:'Özgün / Non-Commodity Kanıt',labelEn:'Original / Non-Commodity Evidence',status:evidenceTypes.length?'STRONG':pages>3?'OPPORTUNITY':'REQUIRES_CONTEXT',confidence:0.72,sourceClass:'INTERNAL_HEURISTIC',commercialRelevance:'CRITICAL',lenses:['SEO','GEO','AEO','LLMO','RAG','E-E-A-T'],evidence:[evidenceTypes.length?`Evidence-bearing structured types detected: ${evidenceTypes.join(', ')}.`:'No Dataset/SoftwareApplication/HowTo/Product-style evidence-bearing type was visible in the aggregate schema summary.',`Public scan boundary: ${pages} pages. First-party novelty against the entire web is not measurable from this scan.`],affectedUrls:affected(pref(scan,'TECH-DUPTITLE')),diagnosisTr:'Genel bilgiyi yeniden anlatan içerikle; özgün veri, metodoloji, hesaplayıcı, karar tablosu, ölçüm veya ilk elden deneyim sunan içerik aynı değerde değildir.',diagnosisEn:'Commodity restatement and first-party data, methodology, calculators, decision artifacts, measurements or experience are not equivalent source assets.',boundaryTr:'Tüm web’e karşı özgünlük iddiası üretilemez; yalnız site içi farklılaşma ve görünür kanıt sinyalleri değerlendirilir.',boundaryEn:'Whole-web novelty cannot be claimed; only within-site differentiation and visible evidence signals are evaluated.'}),
    make({key:'citation_source_readiness',labelTr:'Kaynak / Citation Hazırlığı',labelEn:'Source / Citation Readiness',status:scoreStatus(trust.length+pref(scan,'SCHEMA-ENTITY').length),confidence:0.76,sourceClass:'INTERNAL_HEURISTIC',commercialRelevance:'HIGH',lenses:['GEO','AEO','LLMO','RAG','E-E-A-T'],evidence:ev([...trust,...pref(scan,'SCHEMA-ENTITY')],`Entity-bearing schema types: ${entityTypes.join(', ')||'none reported'}; no trust blocker measured in the public boundary.`),affectedUrls:affected(trust),diagnosisTr:'Kaynak olmaya hazır bir sayfada kimlik, hesap verebilirlik, varlık çözümleme ve doğrulanabilir bilgi zinciri birlikte değerlendirilmelidir.',diagnosisEn:'A source-ready page benefits from clear identity, accountability, entity resolution and a verifiable evidence chain working together.' ,boundaryTr:'Bu bir citation olasılık skoru değildir ve herhangi bir AI sisteminin kaynak göstermesini garanti etmez.',boundaryEn:'This is not a citation-probability score and does not guarantee citation by any AI system.'}),
    make({key:'answer_unit_architecture',labelTr:'Cevap Birimi Mimarisi',labelEn:'Answer-Unit Architecture',status:scoreStatus(answer.length),confidence:0.78,sourceClass:'INTERNAL_HEURISTIC',commercialRelevance:'HIGH',lenses:['AEO','GEO','LLMO','RAG'],evidence:ev(answer,'Title/meta/H1 structural blockers were not measured inside the current crawl boundary.'),affectedUrls:affected(answer),diagnosisTr:'Başlık, H1, açıklama ve sayfa kimliği temiz olduğunda içerik daha küçük, bağımsız cevap birimlerine dönüştürülebilecek daha sağlam bir temele sahip olur.',diagnosisEn:'Clean title, H1, description and page identity provide a stronger foundation for self-contained answer units and retrieval chunks.',boundaryTr:'Gerçek cevap kalitesi ve passage-level retrieval bu public yapısal taramada doğrudan ölçülmez.',boundaryEn:'Actual answer quality and passage-level retrieval are not directly measured by this public structural scan.'}),
    make({key:'entity_resolution_depth',labelTr:'Entity Resolution Derinliği',labelEn:'Entity Resolution Depth',status:entityTypes.length>=3?'STRONG':schemaTypes.length?'OPPORTUNITY':'BLOCKED',confidence:0.84,sourceClass:'MEASURED',commercialRelevance:'HIGH',lenses:['SEO','GEO','LLMO','AAO','E-E-A-T'],evidence:[`Schema types observed: ${schemaTypes.join(', ')||'none'}.`,`Entity-bearing types observed: ${entityTypes.join(', ')||'none'}.`],affectedUrls:affected(byCat(scan,'schema')),diagnosisTr:'Organization, WebSite, WebPage, Product/Service/Person gibi temel varlıkların açık ve tutarlı modellenmesi makine tarafındaki kimlik belirsizliğini azaltır.',diagnosisEn:'Clear, consistent modeling of Organization, WebSite, WebPage and Product/Service/Person entities reduces machine-side identity ambiguity.',boundaryTr:'Aggregate public scan kararlı @id referanslarının tüm site boyunca semantik olarak aynı varlığı gösterdiğini tam kanıtlayamaz.',boundaryEn:'The aggregate public scan cannot fully prove that stable @id references resolve to the same semantic entity across the whole site.'}),
    make({key:'retrieval_surface_coherence',labelTr:'Retrieval Yüzeyi Tutarlılığı',labelEn:'Retrieval-Surface Coherence',status:scoreStatus(llms.length+agent.filter(x=>x.severity!=='info').length),confidence:0.86,sourceClass:'PROPOSAL',commercialRelevance:'MEDIUM',lenses:['GEO','LLMO','AAO','RAG'],evidence:ev([...llms,...agent],`llms score ${scan.scores.llms}/100; optional machine surfaces are evaluated separately from canonical HTML.`),affectedUrls:affected(llms),diagnosisTr:'Canonical HTML ile llms.txt, Markdown veya gerçek API yüzeyleri arasında çelişki olmaması retrieval güvenilirliği için önemlidir.',diagnosisEn:'Canonical HTML and genuine llms.txt, Markdown or API surfaces should not contradict one another if they are used for retrieval.',boundaryTr:'llms.txt ve agent protokolleri zorunlu ranking standardı değildir; eksiklikleri tek başına görünürlük kaybı kanıtlamaz.',boundaryEn:'llms.txt and agent protocols are not mandatory ranking standards; absence alone does not prove a visibility loss.'}),
    make({key:'discovery_graph_coherence',labelTr:'Discovery Graph Tutarlılığı',labelEn:'Discovery-Graph Coherence',status:scoreStatus(discovery.filter(x=>x.severity==='critical'||x.severity==='high').length,discovery.some(x=>x.severity==='critical')),confidence:0.91,sourceClass:'MEASURED',commercialRelevance:'CRITICAL',lenses:['SEO','GEO','RAG','LLMO'],evidence:ev(discovery,'No high-severity robots/sitemap/canonical/internal-link contradiction was measured in the bounded scan.'),affectedUrls:affected(discovery),diagnosisTr:'Robots, sitemap, canonical ve iç linkler aynı final bilgi mimarisini desteklemiyorsa içerik kalitesinden önce discovery zinciri kırılır.',diagnosisEn:'When robots, sitemaps, canonicals and internal links do not support the same final information architecture, discovery breaks before content quality can matter.' ,boundaryTr:'50 sayfalık crawl sınırının dışındaki URL graph’ı bu sonuçta kanıtlanmaz.',boundaryEn:'The URL graph outside the 50-page crawl boundary is not proven by this result.'}),
    make({key:'commercial_path_clarity',labelTr:'Ticari Yol Netliği',labelEn:'Commercial-Path Clarity',status:scoreStatus(conversion.length),confidence:0.75,sourceClass:'INTERNAL_HEURISTIC',commercialRelevance:'CRITICAL',lenses:['SEO','GEO','AEO','E-E-A-T'],evidence:ev(conversion,'A clear CTA/contact path was detected by the bounded public heuristic.'),affectedUrls:affected(conversion),diagnosisTr:'Görünürlük tek başına ticari sonuç değildir; ziyaretçi geldiğinde bir sonraki adımın bulunabilir, güvenli ve anlaşılır olması gerekir.',diagnosisEn:'Visibility is not a commercial outcome by itself; once a visitor arrives, the next action should be discoverable, safe and understandable.' ,boundaryTr:'Bu katman dönüşüm oranı veya gelir tahmini üretmez; yalnız public yol sürtünmesini ölçer.',boundaryEn:'This layer does not estimate conversion rate or revenue; it measures public-path friction only.'}),
    make({key:'trust_accountability',labelTr:'Güven ve Hesap Verebilirlik',labelEn:'Trust & Accountability',status:scoreStatus(trust.length),confidence:0.83,sourceClass:'INTERNAL_HEURISTIC',commercialRelevance:'HIGH',lenses:['SEO','GEO','E-E-A-T','LLMO'],evidence:ev(trust,'About/contact/privacy/entity trust blockers were not measured inside the crawl boundary.'),affectedUrls:affected(trust),diagnosisTr:'Kurumsal kimlik, iletişim, gizlilik, yazarlık ve görünür sorumluluk katmanı hem kullanıcı güveni hem kaynak güvenilirliği açısından ayrı bir kalite boyutudur.',diagnosisEn:'Organization identity, contactability, privacy, authorship and visible accountability form a distinct quality layer for users and source trust.' ,boundaryTr:'E-E-A-T bir tekil makine skoru değildir; bu sinyal yalnız ölçülebilir public trust göstergelerini sınıflandırır.',boundaryEn:'E-E-A-T is not a single machine score; this signal classifies measurable public trust indicators only.'}),
    make({key:'freshness_provenance',labelTr:'Güncellik ve Provenance',labelEn:'Freshness & Provenance',status:'REQUIRES_CONTEXT',confidence:0.9,sourceClass:'MEASURED',commercialRelevance:'MEDIUM',lenses:['SEO','GEO','E-E-A-T','RAG'],evidence:['Current core scan can observe some public date markers but does not expose page-level datePublished/dateModified/sitemap-lastmod parity as a complete dataset.'],affectedUrls:[],diagnosisTr:'Gerçek güncellik; yalnız tarih göstermek değil, görünür değişiklik, structured date ve discovery metadata’sının aynı olayı temsil etmesidir.',diagnosisEn:'Real freshness is not merely displaying a recent date; visible change, structured dates and discovery metadata should represent the same event.' ,boundaryTr:'Keyfî tazelik eşiği veya sahte “son güncelleme” skoru üretilmez; tam analiz için page-level tarih karşılaştırması gerekir.',boundaryEn:'No arbitrary freshness threshold or fake “recently updated” score is produced; full analysis requires page-level date parity.'}),
    make({key:'multimodal_accessibility',labelTr:'Multimodal ve Görsel Anlaşılabilirlik',labelEn:'Multimodal & Visual Understandability',status:a11y.some(x=>x.id.startsWith('A11Y-IMG'))?'OPPORTUNITY':'NOT_MEASURED',confidence:a11y.some(x=>x.id.startsWith('A11Y-IMG'))?0.95:0.68,sourceClass:'MEASURED',commercialRelevance:'MEDIUM',lenses:['SEO','GEO','AEO','E-E-A-T'],evidence:ev(a11y.filter(x=>x.id.startsWith('A11Y-IMG')), 'No missing-alt defect was measured; image quality, surrounding context and visual usefulness are not fully evaluated by the current fetch-only scan.'),affectedUrls:affected(a11y.filter(x=>x.id.startsWith('A11Y-IMG'))),diagnosisTr:'Metinsel içeriği destekleyen görsellerin erişilebilir adı ve bağlamı bulunabilirlik için önemlidir; ancak yalnız alt etiketi kontrolü gerçek görsel kaliteyi kanıtlamaz.',diagnosisEn:'Accessible naming and context for supporting visuals matter for discoverability, but alt-text checks alone cannot prove visual quality.' ,boundaryTr:'Görsel kalite, image understanding ve multimodal relevance için kontrollü görsel analiz gerekir.',boundaryEn:'Visual quality, image understanding and multimodal relevance require controlled visual analysis.'}),
    make({key:'observability_gap',labelTr:'Gerçek Görünürlük / Observability Boşluğu',labelEn:'Observed-Visibility / Observability Gap',status:'REQUIRES_CONTEXT',confidence:1,sourceClass:'MEASURED',commercialRelevance:'CRITICAL',lenses:['SEO','GEO','AEO','LLMO','AAO','RAG'],evidence:['Public URL scanning does not contain private Search Console, analytics, server-log, referral, ranking or provider-side citation data.'],affectedUrls:[],diagnosisTr:'Teknik hazırlık ile gerçekleşmiş gösterim/citation/referral birbirinden ayrılmalıdır. Gerçek performans kanıtı ancak platform veya analytics verisi sağlandığında ölçülebilir.',diagnosisEn:'Technical readiness must be separated from observed impressions, citations and referrals. Actual performance can only be measured when platform or analytics evidence is available.' ,boundaryTr:'Trafik, gelir, ranking veya citation tahmini uydurulmaz. Veri yoksa REQUIRES_CONTEXT kalır.',boundaryEn:'Traffic, revenue, ranking and citation estimates are never fabricated. Without observed data this remains REQUIRES_CONTEXT.'})
  ];
  const actionable=signals.filter(s=>s.status==='BLOCKED'||s.status==='OPPORTUNITY').sort((a,b)=>rank[b.commercialRelevance]-rank[a.commercialRelevance]||b.confidence-a.confidence);
  return {version:OPPORTUNITY_VERSION,classification:'NON_SCORING_ENTERPRISE_OPPORTUNITY_LAYER',canonicalScoreUnchanged:true,domain:scan.domain,scanId:scan.scanId,signals,topOpportunities:actionable.slice(0,6).map((s,i)=>({rank:i+1,key:s.key,status:s.status,commercialRelevance:s.commercialRelevance,confidence:s.confidence})),measuredSignals:signals.filter(s=>!['NOT_MEASURED','REQUIRES_CONTEXT'].includes(s.status)).length,contextRequired:signals.filter(s=>s.status==='REQUIRES_CONTEXT').length,boundaries:['Opportunity signals do not mutate the 12-engine canonical score.','Commercial relevance is a prioritization heuristic, not a traffic or revenue forecast.','Private analytics, Search Console, server logs, backlink/citation corpora and codebase context are never invented.']};
}

const action=(x:OpportunityAction)=>x;
export function generateOpportunityActions(scan:ScanResult):OpportunityAction[]{
  const report=generateOpportunityReport(scan);
  const status=new Map(report.signals.map(s=>[s.key,s.status]));
  const all:OpportunityAction[]=[
    action({key:'discovery_graph_coherence',owner:['DEVELOPER','SEO'],dependencies:[],blastRadius:'SITE_WIDE',changeClass:'DISCOVERY',implementationOrder:10,implementationState:'ACTIONABLE',plan:['Normalize the intended final URL set across robots policy, sitemap, canonicals and internal links.','Remove links to avoidable redirects and reconcile noindex/canonical contradictions before content work.'],acceptanceTests:['Sampled discovery surfaces resolve directly to intended canonical URLs.','No P0/P1 crawl/indexability finding remains on affected URLs.'],regressionTests:['Intentional private/noindex routes remain protected.','SSRF/security boundaries remain unchanged.'],rollback:['Revert only the affected discovery declaration or link map if an intended protected route becomes exposed.'],stopConditions:['Stop if the intended canonical URL cannot be established from public evidence.']}),
    action({key:'query_fanout_coverage',owner:['SEO','CONTENT'],dependencies:['discovery_graph_coherence'],blastRadius:'SECTION',changeClass:'CONTENT',implementationOrder:20,implementationState:'VERIFY_FIRST',plan:['Map each retained page to one primary intent and a non-overlapping set of decision-stage subquestions.','Consolidate true duplicates; otherwise differentiate title, H1, content promise and internal anchors around distinct intents.','Build hub-to-detail paths that expose related subtopics without manufacturing thin pages.'],acceptanceTests:['No retained same-locale priority pages present materially identical title/H1/content promise for the same primary intent.','Each priority subtopic is reachable from a relevant hub through a meaningful internal path.'],regressionTests:['Canonical/sitemap/hreflang references remain aligned after consolidation.'],rollback:['Restore prior route mapping if consolidation removes a demonstrably distinct user intent.'],stopConditions:['Stop consolidation where Search Console/query evidence shows distinct demand that public structure alone cannot resolve.']}),
    action({key:'non_commodity_evidence',owner:['CONTENT','BUSINESS_OWNER'],dependencies:['query_fanout_coverage'],blastRadius:'URL',changeClass:'CONTENT',implementationOrder:30,implementationState:'VERIFY_FIRST',plan:['Add verifiable first-party value to priority pages: original measurements, methodology, decision tables, calculators, observed results, datasets, examples or operational evidence where genuinely available.','Trace factual claims to first-party evidence or explicit external sources; separate observation from interpretation.','Do not increase word count with generic restatement.'],acceptanceTests:['Each remediated priority page contains at least one verifiable evidence unit or original decision artifact that was absent before.','New factual claims are traceable and do not contradict structured data.'],regressionTests:['No duplicate-intent page is created to host generic variations.'],rollback:['Remove any new evidence block that cannot be verified or creates a misleading claim.'],stopConditions:['Stop if no genuine first-party evidence exists; return REQUIRES_CONTEXT rather than inventing data.']}),
    action({key:'answer_unit_architecture',owner:['CONTENT','SEO'],dependencies:['query_fanout_coverage','non_commodity_evidence'],blastRadius:'URL',changeClass:'CONTENT',implementationOrder:40,implementationState:'VERIFY_FIRST',plan:['Place concise self-contained answers immediately under relevant question/decision headings where the page genuinely answers them.','Use lists, tables or step structures only where they improve independent comprehension.','Keep each answer consistent with the page intent and evidence source.'],acceptanceTests:['A human reviewer can identify the primary answer without reading unrelated introduction.','Extracted answer text remains accurate out of immediate surrounding context.'],regressionTests:['Heading hierarchy remains valid and no contradictory answer blocks are introduced.'],rollback:['Revert answer blocks that oversimplify legal/technical meaning or duplicate another canonical page.'],stopConditions:['Stop if the underlying claim lacks evidence or requires professional judgment not present in public context.']}),
    action({key:'entity_resolution_depth',owner:['DEVELOPER','SEO'],dependencies:['discovery_graph_coherence'],blastRadius:'SITE_WIDE',changeClass:'ENTITY',implementationOrder:50,implementationState:'ACTIONABLE',plan:['Normalize stable identifiers for Organization, WebSite, WebPage and factually applicable Product/Service/Person entities.','Reference shared entities instead of duplicating conflicting objects.','Keep structured claims aligned with visible facts and canonical URLs.'],acceptanceTests:['All sampled JSON-LD parses.','Repeated primary entities resolve to stable identifiers and visible facts.'],regressionTests:['No valid existing entity type disappears from pages where it remains applicable.'],rollback:['Restore the last valid graph if a new relationship cannot be supported by public facts.'],stopConditions:['Stop before adding any property that cannot be evidenced on the public site.']}),
    action({key:'citation_source_readiness',owner:['CONTENT','PR_AUTHORITY','BUSINESS_OWNER'],dependencies:['entity_resolution_depth','non_commodity_evidence'],blastRadius:'SECTION',changeClass:'CONTENT',implementationOrder:60,implementationState:'VERIFY_FIRST',plan:['Make accountable identity, authorship/ownership, dates and source provenance explicit where relevant.','Support material claims with first-party evidence or authoritative references without copying source prose.','Build source-worthy pages around original decision value, not citation bait.'],acceptanceTests:['Priority source pages expose accountable identity and traceable claims.','No unsupported endorsement, ranking or citation promise appears.'],regressionTests:['Trust pages and organization identity remain consistent across locales.'],rollback:['Remove claims or attribution that cannot be verified.'],stopConditions:['Stop if authority must be fabricated or borrowed from an unrelated entity.']}),
    action({key:'retrieval_surface_coherence',owner:['DEVELOPER','SEO'],dependencies:['discovery_graph_coherence','entity_resolution_depth'],blastRadius:'SITE_WIDE',changeClass:'TECHNICAL',implementationOrder:70,implementationState:'ACTIONABLE',plan:['Keep canonical HTML as the primary source of truth.','Maintain one root llms.txt as a concise directory and publish page-level Markdown/machine surfaces only when they can remain synchronized.','Validate every linked machine surface and remove stale or contradictory resources.'],acceptanceTests:['Root llms.txt and sampled machine surfaces resolve successfully and do not contradict canonical HTML.'],regressionTests:['llms.txt remains labeled as a proposal; no ranking/citation guarantee is introduced.'],rollback:['Remove any machine surface that becomes stale, contradictory or operationally unsupported.'],stopConditions:['Do not create fake MCP/A2A/OpenAPI surfaces solely to improve a score.']}),
    action({key:'commercial_path_clarity',owner:['BUSINESS_OWNER','CONTENT','DEVELOPER'],dependencies:['discovery_graph_coherence'],blastRadius:'SECTION',changeClass:'CONVERSION',implementationOrder:80,implementationState:'VERIFY_FIRST',plan:['Define one clear next action for each commercial intent page and make the transition to contact, trial, purchase or qualification explicit.','Remove CTA ambiguity and broken/unsafe form paths while preserving user choice.'],acceptanceTests:['Each sampled commercial page exposes a clear next step and destination.','CTA destinations resolve directly and forms remain secure/accessibly labeled.'],regressionTests:['Informational pages are not overloaded with irrelevant sales CTAs.'],rollback:['Restore prior CTA placement if the new flow obscures primary content or harms accessibility.'],stopConditions:['Stop if the correct commercial action depends on business policy not available in public evidence.']}),
    action({key:'trust_accountability',owner:['BUSINESS_OWNER','CONTENT'],dependencies:['entity_resolution_depth'],blastRadius:'SITE_WIDE',changeClass:'ENTITY',implementationOrder:90,implementationState:'VERIFY_FIRST',plan:['Align About, Contact, Privacy, Terms and accountable content ownership with the same real operating identity.','Expose support/contact routes that a user can actually use.'],acceptanceTests:['Trust routes are reachable and identify the same real operator/brand.'],regressionTests:['No invented credential, certification, review or third-party endorsement is introduced.'],rollback:['Remove identity claims that cannot be verified.'],stopConditions:['Stop if legal/operator information requires non-public confirmation.']}),
    action({key:'freshness_provenance',owner:['CONTENT','DEVELOPER'],dependencies:[],blastRadius:'SECTION',changeClass:'MEASUREMENT',implementationOrder:100,implementationState:'CONTEXT_REQUIRED',plan:['Collect page-level visible dates, structured datePublished/dateModified and sitemap lastmod before changing freshness signals.','Update dates only when a real semantic content/data change occurred.'],acceptanceTests:['Visible, structured and discovery dates do not contradict one another on changed pages.'],regressionTests:['Unrelated deploys do not rewrite all lastmod/dateModified values.'],rollback:['Restore prior timestamps when the new value cannot be tied to a real change.'],stopConditions:['No date change without evidence of a real update.']}),
    action({key:'multimodal_accessibility',owner:['CONTENT','DEVELOPER'],dependencies:[],blastRadius:'URL',changeClass:'MULTIMODAL',implementationOrder:110,implementationState:'VERIFY_FIRST',plan:['Correct missing accessible names on meaningful images and ensure surrounding text explains why each visual matters.','Evaluate visual usefulness separately from alt-text compliance before adding or replacing media.'],acceptanceTests:['Meaningful sampled images have accurate accessible alternatives and contextual relevance.'],regressionTests:['Decorative images are not given misleading descriptive alt text.'],rollback:['Restore prior media where replacement reduces information quality.'],stopConditions:['Stop before making claims about image-understanding quality without controlled visual evidence.']}),
    action({key:'observability_gap',owner:['ANALYTICS','SEO','BUSINESS_OWNER'],dependencies:[],blastRadius:'EXTERNAL_DATA',changeClass:'MEASUREMENT',implementationOrder:120,implementationState:'CONTEXT_REQUIRED',plan:['Connect observed evidence sources when available: Search Console generative-AI reporting, analytics/referral data, verified server logs and provider-side mention/citation observations.','Keep readiness metrics separate from observed visibility and commercial outcomes.','Create a before/after ledger keyed to the same domain and implementation release.'],acceptanceTests:['Every reported impression/referral/citation change is traceable to an observed source and time window.','Readiness scores and performance metrics remain separately labeled.'],regressionTests:['No missing private metric is substituted with a heuristic estimate.'],rollback:['Disable the affected observed-data claim if source access or provenance is lost.'],stopConditions:['Do not predict traffic, revenue, ranking or citation when observed data is absent.']})
  ];
  return all.map(a=>status.get(a.key)==='REQUIRES_CONTEXT'?{...a,implementationState:'CONTEXT_REQUIRED' as const}:a).sort((a,b)=>a.implementationOrder-b.implementationOrder);
}
