import registry from './standards-registry.json';
import { runScan as runCoreScan, type Finding, type ScanResult, type Severity, type SourceClass } from './scan-engine';

type RegistryCrawler={token:string;provider:string;purpose:string;importance:string;sourceClass:string;source:string;notes?:string};
const SEARCH_PURPOSES=new Set(['search','user-retrieval','search-ai-context','search-copilot-index']);
const SEVERITY:Record<string,Severity>={critical:'critical',high:'high',medium:'medium',low:'low',info:'info'};

function privateHost(host:string){const h=host.toLowerCase();if(h==='localhost'||h.endsWith('.local')||h.endsWith('.internal'))return true;const p=h.split('.').map(Number);if(p.length===4&&p.every(Number.isFinite)){return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)}return false}
function normalize(input:string){let s=input.trim();if(!/^https?:\/\//i.test(s))s='https://'+s;const u=new URL(s);if(!['http:','https:'].includes(u.protocol)||u.username||u.password||privateHost(u.hostname))throw new Error('Target not allowed');return u}
function parseRobots(text:string){const groups:{agents:string[],rules:{allow:boolean,path:string}[]}[]=[];let g:{agents:string[],rules:{allow:boolean,path:string}[]}={agents:[],rules:[]};for(const raw of text.split(/\r?\n/)){const line=raw.replace(/#.*/,'').trim();if(!line)continue;const m=line.match(/^([^:]+):\s*(.*)$/);if(!m)continue;const key=m[1].trim().toLowerCase(),value=m[2].trim();if(key==='user-agent'){if(g.rules.length){groups.push(g);g={agents:[],rules:[]}}g.agents.push(value.toLowerCase())}else if((key==='allow'||key==='disallow')&&g.agents.length){g.rules.push({allow:key==='allow',path:value})}}if(g.agents.length)groups.push(g);return groups}
function allowed(text:string,token:string,path='/'){if(!text.trim())return null;const groups=parseRobots(text);let selected=groups.filter(g=>g.agents.includes(token.toLowerCase()));if(!selected.length)selected=groups.filter(g=>g.agents.includes('*'));if(!selected.length)return true;let best:{allow:boolean,path:string}|undefined;for(const g of selected)for(const r of g.rules){if(!r.path)continue;const literal=r.path.replace(/\*.*$/,'').replace(/\$$/,'');if(path.startsWith(literal)&&(!best||r.path.length>best.path.length||(r.path.length===best.path.length&&r.allow)))best=r}return best?best.allow:true}
function addUnique(findings:Finding[],f:Finding){if(!findings.some(x=>x.id===f.id&&x.url===f.url))findings.push(f)}
function f(id:string,severity:Severity,titleTr:string,titleEn:string,impactTr:string,impactEn:string,evidence:string,url?:string,sourceClass:SourceClass='OFFICIAL_VENDOR'):Finding{return{id,category:'ai',severity,confidence:'confirmed',sourceClass,titleTr,titleEn,impactTr,impactEn,evidence,url,requiresSource:true}}
function parseLinkHeader(value:string){const out:{url:string;rel:string;type?:string}[]=[];for(const item of value.split(/,(?=\s*<)/)){const u=item.match(/<([^>]+)>/)?.[1];const rel=item.match(/rel=["']?([^"';,]+)["']?/i)?.[1];const type=item.match(/type=["']?([^"';,]+)["']?/i)?.[1];if(u&&rel)out.push({url:u,rel,type})}return out}
function htmlLink(html:string,rel:string,type?:string){const tags=html.match(/<link\b[^>]*>/ig)||[];for(const tag of tags){const r=tag.match(/rel=["']([^"']+)/i)?.[1]||'';if(!r.toLowerCase().split(/\s+/).includes(rel.toLowerCase()))continue;if(type){const t=tag.match(/type=["']([^"']+)/i)?.[1]||'';if(t.toLowerCase()!==type.toLowerCase())continue}const href=tag.match(/href=["']([^"']+)/i)?.[1];if(href)return href}return ''}

export async function runScan(input:string){const result:any=await runCoreScan(input);const base=normalize(result.url||input);let robotsText='';let homeHtml='';let homeHeaders=new Headers();try{const [rr,hr]=await Promise.all([fetch(new URL('/robots.txt',base),{headers:{'user-agent':'HTMLandHTML-Registry/1.0'},signal:AbortSignal.timeout(6000)}),fetch(base,{headers:{'user-agent':'HTMLandHTML-Registry/1.0','accept':'text/html'},signal:AbortSignal.timeout(6000)})]);if(rr.ok)robotsText=await rr.text();if(hr.ok){homeHtml=await hr.text();homeHeaders=hr.headers}}catch{}
const crawlerMatrix:any={};let discoverable=0,totalDiscoverable=0;for(const c of registry.crawlers as RegistryCrawler[]){const a=robotsText?allowed(robotsText,c.token,'/'):null;const searchRelevant=SEARCH_PURPOSES.has(c.purpose);crawlerMatrix[c.token]={provider:c.provider,purpose:c.purpose,allowed:a,searchRelevant,source:c.source,notes:c.notes||null};if(searchRelevant){totalDiscoverable++;if(a!==false)discoverable++;if(a===false){const sev=SEVERITY[c.importance]||'medium';addUnique(result.findings,f(`AI-POLICY-${c.token.toUpperCase().replace(/[^A-Z0-9]/g,'-')}`,sev,`${c.provider} ${c.token} erişimi engellenmiş`,`${c.provider} ${c.token} access is blocked`,`${c.provider} arama veya kullanıcı yönlendirmeli retrieval görünürlüğü azalabilir.`,`${c.provider} search or user-directed retrieval visibility may be reduced.`,`robots.txt => ${c.token} disallow /`,base.href,c.sourceClass as SourceClass))}}}
for(const c of registry.crawlers as RegistryCrawler[]){if(!SEARCH_PURPOSES.has(c.purpose)&&crawlerMatrix[c.token]?.allowed===false){addUnique(result.findings,{id:`AI-CONTROL-${c.token.toUpperCase().replace(/[^A-Z0-9]/g,'-')}`,category:'ai',severity:'info',confidence:'confirmed',sourceClass:c.sourceClass as SourceClass,titleTr:`${c.token} kullanım tercihi: engelli`,titleEn:`${c.token} usage preference: blocked`,impactTr:'Bu sinyal arama görünürlüğü problemi olarak cezalandırılmaz; training/grounding/ads kontrolü ayrı kullanıcı tercihidir.',impactEn:'This is not penalized as a search visibility defect; training/grounding/ads control is a separate publisher choice.',evidence:`robots.txt => ${c.token} disallow /`,url:base.href,requiresSource:true})}}
// v2 correctness: blockquote summary is recommended but optional, so never score it as a format failure.
result.findings=result.findings.filter((x:Finding)=>x.id!=='LLMS-SUMMARY-001');
const headerLinks=parseLinkHeader(homeHeaders.get('link')||'');const described=htmlLink(homeHtml,'describedby')||headerLinks.find(x=>x.rel.toLowerCase().includes('describedby'))?.url||'';const markdown=htmlLink(homeHtml,'alternate','text/markdown')||headerLinks.find(x=>x.rel.toLowerCase().includes('alternate')&&(x.type||'').toLowerCase()==='text/markdown')?.url||'';
const v2=result.summary?.llmsLinks!==undefined;const llmsDiscovery={describedby:Boolean(described),describedbyTarget:described||null,markdownAlternate:Boolean(markdown),markdownTarget:markdown||null,proposalVersion:'v2 / 2026-08'};
if(result.scores?.ai!=null&&totalDiscoverable){const access=Math.round(discoverable/totalDiscoverable*100);const structural=Math.max(0,Math.min(100,Number(result.scores.ai)||0));result.scores.ai=Math.round(access*.72+structural*.28)}
const weight:any={crawl:12,technical:14,ai:12,llms:6,schema:8,performance:10,accessibility:9,security:10,trust:7,agent:3,conversion:4,links:5};let numerator=0,denominator=0;for(const [k,w] of Object.entries(weight)){if(typeof result.scores?.[k]==='number'){numerator+=result.scores[k]*Number(w);denominator+=Number(w)}}if(denominator)result.overall=Math.round(numerator/denominator);
const confidenceCount:any={confirmed:0,strong:0,probable:0,'requires-source-verification':0};for(const x of result.findings)confidenceCount[x.confidence]=(confidenceCount[x.confidence]||0)+1;const measured=result.findings.filter((x:Finding)=>x.confidence==='confirmed').length;result.registry={version:registry.registryVersion,verifiedAt:registry.verifiedAt,policies:registry.policies.map((p:any)=>({id:p.id,name:p.name,status:p.status,version:p.version,source:p.source}))};result.engine={name:'HTML&HTML Evidence Engine',version:'3.0.0',architecture:'deterministic-core+versioned-standards-orchestrator'};result.policies=crawlerMatrix;result.llmsV2=llmsDiscovery;result.evidenceQuality={findingCount:result.findings.length,confirmed:measured,confidence:confidenceCount,confirmedRatio:result.findings.length?Math.round(measured/result.findings.length*100):100};result.limitations=[...(result.limitations||[]),'Crawler policy checks evaluate published robots.txt rules. They do not prove that vendor-origin IPs bypass every WAF/CDN control.','llms.txt remains a proposal; absence is not treated as a search-ranking failure.','Field Core Web Vitals are not fabricated when CrUX/PageSpeed evidence is unavailable.'];
const rank:any={critical:0,high:1,medium:2,low:3,info:4};result.findings.sort((a:Finding,b:Finding)=>rank[a.severity]-rank[b.severity]||a.id.localeCompare(b.id));return result as ScanResult & Record<string,any>}
