export type Severity='critical'|'high'|'medium'|'low'|'info';
export type Confidence='confirmed'|'strong'|'probable'|'requires-source-verification';
export type SourceClass='OFFICIAL_STANDARD'|'OFFICIAL_VENDOR'|'PROPOSAL'|'MEASURED'|'INTERNAL_HEURISTIC'|'EXPERIMENTAL';
export type Category='crawl'|'technical'|'ai'|'llms'|'schema'|'performance'|'accessibility'|'security'|'trust'|'agent'|'conversion'|'links';
export type Finding={id:string;category:Category;severity:Severity;confidence:Confidence;sourceClass:SourceClass;titleTr:string;titleEn:string;impactTr:string;impactEn:string;evidence:string;url?:string;requiresSource:boolean};
export type ScanResult={scanId:string;domain:string,url:string,scannedAt:string,checked:number,overall:number,scores:Record<Category,number>,findings:Finding[],summary:any,policies:any,fieldData:any};

type FetchResult={response:Response;text:string;url:URL;redirects:number;bytes:number};
type Page={url:URL,status:number,html:string,bytes:number,headers:Headers,title:string,description:string,h1:number,canonical:string,lang:string,robotsMeta:string,schemaBlocks:string[],text:string,links:string[],images:number,imagesMissingAlt:number,inputs:number,unlabelledInputs:number,buttonsWithoutName:number,scripts:number,styles:number,blockingHeadScripts:number,mixedContent:number,forms:number,insecureForms:number,ctaCount:number,hasAuthor:boolean,hasDate:boolean};

type Rule={ok:boolean|null;weight:number};
const UA='HTMLandHTML-Validator/2.0 (+https://htmlandhtml.com)';
const MAX_BYTES=1_000_000,MAX_REDIRECTS=4,MAX_PAGES=50,MAX_LINK_PROBES=30,TIMEOUT_MS=7000;
const REDIRECTS=new Set([301,302,303,307,308]);
const CATEGORIES:Category[]=['crawl','technical','ai','llms','schema','performance','accessibility','security','trust','agent','conversion','links'];
const privateName=(h:string)=>h==='localhost'||h.endsWith('.localhost')||h.endsWith('.local')||h.endsWith('.internal')||h.endsWith('.home.arpa');
function ipv4Parts(ip:string){const p=ip.split('.');if(p.length!==4||p.some(x=>!/^\d+$/.test(x)||+x>255))return null;return p.map(Number)}
function privateIPv4(ip:string){const p=ipv4Parts(ip);if(!p)return false;return p[0]===10||p[0]===127||p[0]===0||(p[0]===169&&p[1]===254)||(p[0]===172&&p[1]>=16&&p[1]<=31)||(p[0]===192&&p[1]===168)||(p[0]===100&&p[1]>=64&&p[1]<=127)||(p[0]===198&&(p[1]===18||p[1]===19))||p[0]>=224}
function privateIPv6(ip:string){const v=ip.toLowerCase();return v==='::1'||v==='::'||v.startsWith('fc')||v.startsWith('fd')||v.startsWith('fe8')||v.startsWith('fe9')||v.startsWith('fea')||v.startsWith('feb')||v.startsWith('::ffff:127.')||v.startsWith('::ffff:10.')||v.startsWith('::ffff:192.168.')}
function normalize(input:string){let s=input.trim();if(!/^https?:\/\//i.test(s))s='https://'+s;const u=new URL(s);if(!['https:','http:'].includes(u.protocol))throw new Error('Only HTTP/HTTPS supported');if(u.username||u.password)throw new Error('Credentials in URL are not allowed');if(u.port&&!['80','443'].includes(u.port))throw new Error('Non-standard ports are not allowed');const h=u.hostname.toLowerCase().replace(/^\[|\]$/g,'');if(privateName(h)||privateIPv4(h)||privateIPv6(h)||h.includes(':'))throw new Error('Private or local targets are not allowed');u.hash='';return u}
async function resolvePublic(host:string){if(privateName(host)||privateIPv4(host)||privateIPv6(host)||host.includes(':'))throw new Error('Private or local targets are not allowed');const headers={accept:'application/dns-json'};const qs=encodeURIComponent(host);const [a,aaaa]=await Promise.allSettled([fetch(`https://cloudflare-dns.com/dns-query?name=${qs}&type=A`,{headers,signal:AbortSignal.timeout(3500)}),fetch(`https://cloudflare-dns.com/dns-query?name=${qs}&type=AAAA`,{headers,signal:AbortSignal.timeout(3500)})]);let answers:string[]=[];for(const item of [a,aaaa]){if(item.status!=='fulfilled'||!item.value.ok)continue;try{const j:any=await item.value.json();answers.push(...(j.Answer||[]).map((x:any)=>String(x.data||'')))}catch{}}
if(!answers.length)throw new Error('DNS resolution failed');for(const ip of answers){if(privateIPv4(ip)||privateIPv6(ip))throw new Error('Target resolves to a private or reserved address')}
}
async function readLimited(r:Response){const len=Number(r.headers.get('content-length')||0);if(len>MAX_BYTES)throw new Error('Response exceeds scan size limit');if(!r.body)return '';const reader=r.body.getReader();const chunks:Uint8Array[]=[];let total=0;while(true){const {done,value}=await reader.read();if(done)break;if(value){total+=value.byteLength;if(total>MAX_BYTES){reader.cancel();throw new Error('Response exceeds scan size limit')}chunks.push(value)}}const out=new Uint8Array(total);let pos=0;for(const c of chunks){out.set(c,pos);pos+=c.byteLength}return new TextDecoder().decode(out)}
async function safeFetch(input:URL,method:'GET'|'HEAD'='GET'):Promise<FetchResult>{let u=normalize(input.toString());let redirects=0;while(true){await resolvePublic(u.hostname);const r=await fetch(u,{method,redirect:'manual',headers:{'user-agent':UA,'accept':'text/html,text/plain,application/xml,application/json,*/*'},signal:AbortSignal.timeout(TIMEOUT_MS)});if(REDIRECTS.has(r.status)){if(++redirects>MAX_REDIRECTS)throw new Error('Too many redirects');const loc=r.headers.get('location');if(!loc)throw new Error('Redirect without location');u=normalize(new URL(loc,u).toString());continue}const text=method==='HEAD'?'':await readLimited(r.clone());return {response:r,text,url:u,redirects,bytes:new TextEncoder().encode(text).byteLength}}
}
function escRe(s:string){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function meta(html:string,name:string){const n=escRe(name);return html.match(new RegExp(`<meta[^>]+(?:name|property)=["']${n}["'][^>]+content=["']([^"']*)["']`,'i'))?.[1]||html.match(new RegExp(`<meta[^>]+content=["']([^"']*)["'][^>]+(?:name|property)=["']${n}["']`,'i'))?.[1]||''}
function relLink(html:string,rel:string,type?:string){const tags=html.match(/<link\b[^>]*>/ig)||[];for(const tag of tags){const r=tag.match(/rel=["']([^"']+)/i)?.[1]||'';if(!r.toLowerCase().split(/\s+/).includes(rel.toLowerCase()))continue;if(type){const t=tag.match(/type=["']([^"']+)/i)?.[1]||'';if(t.toLowerCase()!==type.toLowerCase())continue}const h=tag.match(/href=["']([^"']+)/i)?.[1];if(h)return h}return ''}
function strip(html:string){return html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&[a-z0-9#]+;/gi,' ').replace(/\s+/g,' ').trim()}
function attr(tag:string,name:string){return tag.match(new RegExp(`${name}\\s*=\\s*["']([^"']*)["']`,'i'))?.[1]||''}
function internalLinks(html:string,base:URL,limit=120){const out:string[]=[];const re=/<a\b[^>]*href=["']([^"'#]+)["'][^>]*>/ig;let m;while((m=re.exec(html))&&out.length<limit){try{const u=new URL(m[1],base);u.hash='';if(u.origin===base.origin&&['http:','https:'].includes(u.protocol)&&!out.includes(u.href)&&!/(\.(?:jpg|jpeg|png|gif|webp|svg|pdf|zip|mp4|mp3))($|\?)/i.test(u.pathname))out.push(u.href)}catch{}}return out}
function pageFrom(f:FetchResult):Page{const html=f.text,base=f.url;const title=html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)?.[1]?.replace(/\s+/g,' ').trim()||'';const h1=(html.match(/<h1\b/ig)||[]).length;const schemaBlocks=(html.match(/<script[^>]+type=["']application\/ld\+json["'][^>]*>[\s\S]*?<\/script>/ig)||[]).map(x=>x.replace(/^<script[^>]*>/i,'').replace(/<\/script>$/i,'').trim());const imgs=html.match(/<img\b[^>]*>/ig)||[];const inputs=html.match(/<(?:input|select|textarea)\b[^>]*>/ig)||[];const labels=html.match(/<label\b[^>]*for=["']([^"']+)["'][^>]*>/ig)||[];const labelFor=new Set(labels.map(x=>attr(x,'for')).filter(Boolean));let unlabelled=0;for(const i of inputs){const type=attr(i,'type').toLowerCase();if(type==='hidden'||type==='submit'||type==='button')continue;const id=attr(i,'id');if(!attr(i,'aria-label')&&!attr(i,'aria-labelledby')&&!(id&&labelFor.has(id)))unlabelled++}const buttons=html.match(/<(?:button|a)\b[^>]*>[\s\S]*?<\/(?:button|a)>/ig)||[];let unnamed=0;for(const b of buttons){const body=strip(b);if(!body&&!attr(b,'aria-label')&&!attr(b,'title'))unnamed++}const head=html.match(/<head\b[^>]*>([\s\S]*?)<\/head>/i)?.[1]||'';const blocking=(head.match(/<script\b(?![^>]*(?:async|defer|type=["']module["']))[^>]*src=/ig)||[]).length;const links=internalLinks(html,base);const text=strip(html);const cta=(html.match(/<(?:a|button)\b[^>]*>[^<]*(?:buy|start|try|contact|book|demo|quote|checkout|pricing|satın|başla|iletişim|teklif|randevu)[^<]*<\/(?:a|button)>/ig)||[]).length;return {url:base,status:f.response.status,html,bytes:f.bytes,headers:f.response.headers,title,description:meta(html,'description'),h1,canonical:relLink(html,'canonical'),lang:html.match(/<html[^>]+lang=["']([^"']+)/i)?.[1]||'',robotsMeta:meta(html,'robots').toLowerCase(),schemaBlocks,text,links,images:imgs.length,imagesMissingAlt:imgs.filter(x=>!(/\balt\s*=/i.test(x))).length,inputs:inputs.length,unlabelledInputs:unlabelled,buttonsWithoutName:unnamed,scripts:(html.match(/<script\b/ig)||[]).length,styles:(html.match(/<link\b[^>]+rel=["'][^"']*stylesheet/ig)||[]).length,blockingHeadScripts:blocking,mixedContent:base.protocol==='https:'?(html.match(/(?:src|href|action)=["']http:\/\//ig)||[]).length:0,forms:(html.match(/<form\b/ig)||[]).length,insecureForms:base.protocol==='https:'?(html.match(/<form\b[^>]+action=["']http:\/\//ig)||[]).length:0,ctaCount:cta,hasAuthor:/\b(?:author|yazar|written by|tarafından)\b/i.test(text)||/rel=["']author/i.test(html),hasDate:/<time\b/i.test(html)||/\b(?:datePublished|dateModified)\b/.test(html)}}
function add(a:Finding[],x:Finding){if(!a.some(y=>y.id===x.id&&y.url===x.url))a.push(x)}
function finding(id:string,category:Category,severity:Severity,confidence:Confidence,sourceClass:SourceClass,titleTr:string,titleEn:string,impactTr:string,impactEn:string,evidence:string,url?:string,requiresSource=false):Finding{return {id,category,severity,confidence,sourceClass,titleTr,titleEn,impactTr,impactEn,evidence,url,requiresSource}}
function score(rules:Rule[]){let den=0,num=0;for(const r of rules){if(r.ok===null)continue;den+=r.weight;if(r.ok)num+=r.weight}return den?Math.round(num/den*100):100}
function robotsGroups(text:string){const groups:{agents:string[],rules:{kind:'allow'|'disallow',path:string}[]}[]=[];let g:{agents:string[],rules:{kind:'allow'|'disallow',path:string}[]}={agents:[],rules:[]};for(const raw of text.split(/\r?\n/)){const line=raw.replace(/#.*/,'').trim();if(!line)continue;const m=line.match(/^([^:]+):\s*(.*)$/);if(!m)continue;const k=m[1].trim().toLowerCase(),v=m[2].trim();if(k==='user-agent'){if(g.rules.length){groups.push(g);g={agents:[],rules:[]}}g.agents.push(v.toLowerCase())}else if((k==='allow'||k==='disallow')&&g.agents.length)g.rules.push({kind:k as any,path:v})}if(g.agents.length)groups.push(g);return groups}
function robotAllowed(text:string,token:string,path='/'){if(!text.trim())return null;const t=token.toLowerCase();const groups=robotsGroups(text);let selected=groups.filter(g=>g.agents.includes(t));if(!selected.length)selected=groups.filter(g=>g.agents.includes('*'));if(!selected.length)return true;let best:{kind:'allow'|'disallow',path:string}|null=null;for(const g of selected)for(const r of g.rules){if(!r.path)continue;const p=r.path.replace(/\*.*$/,'');if(path.startsWith(p)&&(!best||r.path.length>best.path.length||(r.path.length===best.path.length&&r.kind==='allow')))best=r}return !best||best.kind==='allow'}
function sitemapUrls(xml:string,base:URL){const out:string[]=[];const re=/<loc>\s*([^<]+)\s*<\/loc>/ig;let m;while((m=re.exec(xml))&&out.length<MAX_PAGES*2){try{const u=new URL(m[1].trim(),base);if(u.origin===base.origin&&!out.includes(u.href))out.push(u.href)}catch{}}return out}
function llmsValid(text:string){const h1=/^#\s+\S+/m.test(text),summary=/^>\s+\S+/m.test(text),links=(text.match(/^\s*-\s+\[[^\]]+\]\(https?:\/\/[^)]+\)/gm)||[]);return {h1,summary,links}}
function extractSchema(blocks:string[]){const parsed:any[]=[];let invalid=0;for(const b of blocks){try{const x=JSON.parse(b);parsed.push(x)}catch{invalid++}}const flat:any[]=[];const walk=(x:any)=>{if(!x)return;if(Array.isArray(x))x.forEach(walk);else if(typeof x==='object'){if(Array.isArray(x['@graph']))x['@graph'].forEach(walk);flat.push(x)}};parsed.forEach(walk);return {parsed:flat,invalid,types:[...new Set(flat.flatMap(x=>Array.isArray(x['@type'])?x['@type']:[x['@type']]).filter(Boolean).map(String))]}}
async function probe(url:string){try{let x=await safeFetch(new URL(url),'HEAD');if(x.response.status===405||x.response.status===403)x=await safeFetch(new URL(url),'GET');return x.response.status}catch{return 0}}
async function root(base:URL,path:string){try{const x=await safeFetch(new URL(path,base));return {ok:x.response.ok,status:x.response.status,text:x.text,headers:x.response.headers,url:x.url}}catch(e:any){return {ok:false,status:0,text:'',headers:new Headers(),url:new URL(path,base),error:e?.message||'fetch failed'}}}

export async function runScan(input:string):Promise<ScanResult>{const start=normalize(input);const first=await safeFetch(start);if(!(first.response.headers.get('content-type')||'').toLowerCase().includes('text/html'))throw new Error('Target is not HTML');const home=pageFrom(first);const base=home.url;const findings:Finding[]=[];let checked=0;
const [robots,sitemap,llms,agentCard,openapi,mcp]=await Promise.all([root(base,'/robots.txt'),root(base,'/sitemap.xml'),root(base,'/llms.txt'),root(base,'/.well-known/agent-card.json'),root(base,'/openapi.json'),root(base,'/mcp')]);checked+=6;
const discovered=[base.href,...sitemapUrls(sitemap.text,base),...home.links];const unique=[...new Set(discovered)].filter(x=>{try{return new URL(x).origin===base.origin}catch{return false}}).slice(0,MAX_PAGES);const pages:Page[]=[home];for(let i=1;i<unique.length;i+=4){const batch=unique.slice(i,i+4);const got=await Promise.all(batch.map(async u=>{try{const f=await safeFetch(new URL(u));if(!(f.response.headers.get('content-type')||'').toLowerCase().includes('text/html'))return null;return pageFrom(f)}catch{return null}}));for(const p of got)if(p)pages.push(p)}checked+=pages.length;
const titles=new Map<string,string[]>(),canonicals=new Map<string,string[]>();for(const p of pages){if(p.title){const k=p.title.toLowerCase();titles.set(k,[...(titles.get(k)||[]),p.url.href])}if(p.canonical){const k=p.canonical;canonicals.set(k,[...(canonicals.get(k)||[]),p.url.href])}
if(p.status>=400)add(findings,finding('CRAWL-HTTP-001','crawl','critical','confirmed','MEASURED','Sayfa HTTP hatası veriyor','Page returns an HTTP error','Tarama ve kullanıcı erişimi doğrudan etkilenir.','Directly impacts crawling and user access.',`HTTP ${p.status}`,p.url.href));
if(!p.title)add(findings,finding('TECH-TITLE-001','technical','high','confirmed','OFFICIAL_STANDARD','Title etiketi yok','Missing title tag','Arama sonucu ve belge kimliği zayıflar.','Weakens search result and document identity.','<title> not found',p.url.href,true));
if(!p.description)add(findings,finding('TECH-META-001','technical','medium','confirmed','MEASURED','Meta description yok','Missing meta description','Arama snippet kontrolü azalır.','Reduces control over search snippets.','meta[name=description] not found',p.url.href,true));
if(p.h1!==1)add(findings,finding('TECH-H1-001','technical','medium','confirmed','MEASURED','H1 hiyerarşisi tutarsız','Inconsistent H1 hierarchy','Ana konu sinyali ve erişilebilir belge yapısı zayıflar.','Weakens primary topic signaling and accessible document structure.',`${p.h1} H1`,p.url.href,true));
if(!p.canonical)add(findings,finding('TECH-CANON-001','technical','high','confirmed','OFFICIAL_STANDARD','Canonical bulunamadı','Canonical missing','URL birleştirme sinyali eksik kalır.','Canonicalization signal is missing.','rel=canonical not found',p.url.href,true));
if(p.robotsMeta.includes('noindex'))add(findings,finding('TECH-NOINDEX-001','technical','critical','confirmed','OFFICIAL_STANDARD','Sayfa noindex','Page is noindex','Sayfa arama indeksinden çıkarılabilir.','Page may be excluded from search indexes.',p.robotsMeta,p.url.href,true));
if(!p.lang)add(findings,finding('A11Y-LANG-001','accessibility','medium','confirmed','OFFICIAL_STANDARD','Belge dili tanımlı değil','Document language is missing','Ekran okuyucu telaffuzu ve dil ayrıştırması etkilenir.','Affects screen-reader pronunciation and language parsing.','html[lang] missing',p.url.href,true));
if(p.imagesMissingAlt)add(findings,finding('A11Y-IMG-001','accessibility','medium','confirmed','OFFICIAL_STANDARD','Alt metinsiz görseller var','Images without alt text','Erişilebilirlik ve görsel bağlam kaybolur.','Accessibility and image context are reduced.',`${p.imagesMissingAlt}/${p.images} images missing alt`,p.url.href,true));
if(p.unlabelledInputs)add(findings,finding('A11Y-FORM-001','accessibility','high','confirmed','OFFICIAL_STANDARD','Etiketsiz form alanları var','Form controls without accessible labels','Form kullanımı yardımcı teknolojilerde bozulabilir.','Forms may fail for assistive technologies.',`${p.unlabelledInputs} unlabeled controls`,p.url.href,true));
if(p.buttonsWithoutName)add(findings,finding('A11Y-NAME-001','accessibility','medium','confirmed','OFFICIAL_STANDARD','Erişilebilir adı olmayan etkileşimler var','Interactive controls lack accessible names','Klavye ve ekran okuyucu deneyimi bozulabilir.','Keyboard and screen-reader experience may degrade.',`${p.buttonsWithoutName} unnamed controls`,p.url.href,true));
if(p.bytes>500000)add(findings,finding('PERF-HTML-001','performance','high','confirmed','MEASURED','HTML yanıtı çok büyük','HTML response is oversized','İlk yanıt ve ayrıştırma maliyeti yükselir.','Increases initial transfer and parsing cost.',`${p.bytes} bytes HTML`,p.url.href,true));else if(p.bytes>250000)add(findings,finding('PERF-HTML-001','performance','medium','confirmed','MEASURED','HTML yanıtı ağır','HTML response is heavy','İlk yükleme maliyetini artırabilir.','May increase initial load cost.',`${p.bytes} bytes HTML`,p.url.href,true));
if(p.blockingHeadScripts>2)add(findings,finding('PERF-BLOCK-001','performance','medium','confirmed','MEASURED','Render-blocking script yoğunluğu yüksek','High render-blocking script count','İlk render gecikebilir.','May delay first render.',`${p.blockingHeadScripts} blocking head scripts`,p.url.href,true));
if(p.mixedContent)add(findings,finding('SEC-MIXED-001','security','high','confirmed','OFFICIAL_STANDARD','HTTPS sayfada HTTP kaynakları var','Mixed content detected','Tarayıcı güvenliği ve kaynak yükleme davranışı etkilenebilir.','Browser security and resource loading may be affected.',`${p.mixedContent} insecure references`,p.url.href,true));
if(p.insecureForms)add(findings,finding('SEC-FORM-001','security','critical','confirmed','OFFICIAL_STANDARD','Form verisi HTTP hedefe gönderiliyor','Form submits to HTTP','Kullanıcı verisi şifrelenmeden iletilebilir.','User data may be transmitted without transport encryption.',`${p.insecureForms} insecure forms`,p.url.href,true));}
for(const [t,urls] of titles)if(urls.length>1)add(findings,finding('TECH-DUPTITLE-001','technical','medium','confirmed','MEASURED','Aynı title birden fazla sayfada','Duplicate titles across pages','Sayfa ayrışması zayıflar.','Weakens page differentiation.',`${urls.length} pages share: ${t.slice(0,120)}`,urls[0],true));
if(!robots.ok)add(findings,finding('CRAWL-ROBOTS-001','crawl','medium','confirmed','OFFICIAL_STANDARD','robots.txt erişilemiyor','robots.txt unavailable','Crawler erişim politikası açıkça yayınlanmıyor.','Crawler access policy is not explicitly published.',`HTTP ${robots.status}`));
if(!sitemap.ok)add(findings,finding('CRAWL-SITEMAP-001','crawl','medium','confirmed','OFFICIAL_STANDARD','sitemap.xml erişilemiyor','sitemap.xml unavailable','URL keşfi ve kapsam görünürlüğü azalır.','Reduces URL discovery and coverage visibility.',`HTTP ${sitemap.status}`));
const botDefs=[['Googlebot','search','critical','OFFICIAL_VENDOR'],['OAI-SearchBot','search','high','OFFICIAL_VENDOR'],['Claude-SearchBot','search','high','OFFICIAL_VENDOR'],['Claude-User','retrieval','medium','OFFICIAL_VENDOR'],['PerplexityBot','search','high','OFFICIAL_VENDOR'],['GPTBot','training','info','OFFICIAL_VENDOR'],['ClaudeBot','training','info','OFFICIAL_VENDOR'],['Google-Extended','training/grounding-control','info','OFFICIAL_VENDOR']] as const;const policies:any={};for(const [bot,purpose,sev,src] of botDefs){const allowed=robots.ok?robotAllowed(robots.text,bot):null;policies[bot]={allowed,purpose};checked++;if(allowed===false&&(purpose==='search'||purpose==='retrieval'))add(findings,finding(`AI-ROBOTS-${bot.toUpperCase().replace(/[^A-Z0-9]/g,'-')}`,'ai',sev as Severity,'confirmed',src as SourceClass,`${bot} erişimi engellenmiş`,`${bot} access is blocked`,purpose==='search'?'İlgili AI arama görünürlüğü azalabilir.':'Kullanıcı yönlendirmeli AI erişimi engellenebilir.',purpose==='search'?'May reduce visibility in the related AI search experience.':'May block user-directed AI retrieval.',`robots.txt => ${bot} disallow /`,undefined,true))}
const lv=llmsValid(llms.text);if(!llms.ok)add(findings,finding('LLMS-ROOT-001','llms','low','confirmed','PROPOSAL','llms.txt bulunamadı','llms.txt not found','Agent keşfi için isteğe bağlı makine-okunabilir rehber yok.','Optional machine-readable agent guidance is absent.',`HTTP ${llms.status}`));else{if(!lv.h1)add(findings,finding('LLMS-FORMAT-001','llms','medium','confirmed','PROPOSAL','llms.txt H1 başlığı eksik','llms.txt is missing its H1','Önerilen v2 formatının zorunlu bölümü eksik.','Required section of the v2 proposal is missing.','# heading not found',llms.url.href,true));if(!lv.summary)add(findings,finding('LLMS-SUMMARY-001','llms','low','confirmed','PROPOSAL','llms.txt kısa özeti yok','llms.txt has no blockquote summary','Agent bağlamı daha az yönlendirilmiş olur.','Agent context is less guided.','blockquote summary not found',llms.url.href,true));const linked=lv.links.slice(0,10);for(const l of linked){const u=l.match(/\((https?:\/\/[^)]+)\)/)?.[1];if(u){const s=await probe(u);checked++;if(!(s>=200&&s<400))add(findings,finding('LLMS-LINK-001','llms','medium','confirmed','PROPOSAL','llms.txt içinde bozuk bağlantı','Broken link inside llms.txt','Agent rehberindeki kaynak erişilemiyor.','A resource in the agent guide is unreachable.',`HTTP ${s} ${u}`,u,true))}}}
const described=relLink(home.html,'describedby'),mdAlt=relLink(home.html,'alternate','text/markdown');if(llms.ok&&!described)add(findings,finding('LLMS-DISCOVERY-001','llms','low','confirmed','PROPOSAL','llms.txt discoverability linki yok','No llms.txt discoverability link','v2 önerisindeki rel=describedby sinyali yayınlanmıyor.','The v2 proposal rel=describedby signal is absent.','rel=describedby not found',base.href,true));if(!mdAlt)add(findings,finding('LLMS-MD-001','llms','info','confirmed','PROPOSAL','Markdown alternate bulunamadı','No Markdown alternate found','Agentlara temiz içerik alternatifi sunulmuyor.','No clean Markdown alternate is advertised.','rel=alternate type=text/markdown not found',base.href,true));
const schema=extractSchema(pages.flatMap(p=>p.schemaBlocks));checked+=pages.reduce((a,p)=>a+p.schemaBlocks.length,0);if(!schema.parsed.length)add(findings,finding('SCHEMA-NONE-001','schema','medium','confirmed','OFFICIAL_STANDARD','Geçerli JSON-LD bulunamadı','No valid JSON-LD found','Makine-okunabilir varlık ve içerik tanımı sınırlı kalır.','Machine-readable entity and content definition is limited.','0 valid JSON-LD blocks',base.href,true));if(schema.invalid)add(findings,finding('SCHEMA-JSON-001','schema','high','confirmed','OFFICIAL_STANDARD','Geçersiz JSON-LD var','Invalid JSON-LD detected','Yapılandırılmış veri ayrıştırılamaz.','Structured data cannot be parsed.',`${schema.invalid} invalid blocks`,base.href,true));const entityTypes=schema.types.filter(x=>/Organization|LocalBusiness|Person|Product|Article|WebSite/i.test(x));if(schema.parsed.length&&!entityTypes.length)add(findings,finding('SCHEMA-ENTITY-001','schema','low','strong','INTERNAL_HEURISTIC','Ana varlık tipi net değil','Primary entity type is unclear','Varlık bağlamı makineler için daha zayıf olabilir.','Entity context may be weaker for machines.',`types: ${schema.types.join(', ')||'none'}`,base.href,true));
const hdr=home.headers;const securityRules=[['SEC-HSTS-001','strict-transport-security','HSTS yok','HSTS missing','medium'],['SEC-CSP-001','content-security-policy','CSP yok','CSP missing','medium'],['SEC-NOSNIFF-001','x-content-type-options','nosniff yok','nosniff missing','low'],['SEC-REF-001','referrer-policy','Referrer-Policy yok','Referrer-Policy missing','low'],['SEC-PERM-001','permissions-policy','Permissions-Policy yok','Permissions-Policy missing','low']] as const;for(const [id,h,tr,en,sev] of securityRules){checked++;if(!hdr.get(h))add(findings,finding(id,'security',sev as Severity,'confirmed','OFFICIAL_STANDARD',tr,en,'Tarayıcı güvenlik sertleştirmesi eksik.','Browser security hardening is incomplete.',`${h} header missing`,base.href,true))}
const trustText=pages.map(p=>p.text.toLowerCase()).join(' '),allLinks=pages.flatMap(p=>p.links);const hasAbout=allLinks.some(x=>/\/(about|hakkimizda|hakkımızda)(\/|$)/i.test(new URL(x).pathname)),hasContact=allLinks.some(x=>/\/(contact|iletisim|iletişim)(\/|$)/i.test(new URL(x).pathname))||/mailto:|tel:/i.test(pages.map(p=>p.html).join(' ')),hasPrivacy=allLinks.some(x=>/\/(privacy|gizlilik|kvkk)(\/|$)/i.test(new URL(x).pathname)),hasTerms=allLinks.some(x=>/\/(terms|terms-of-service|kosullar|koşullar|sartlar|şartlar)(\/|$)/i.test(new URL(x).pathname));if(!hasAbout)add(findings,finding('TRUST-ABOUT-001','trust','low','strong','INTERNAL_HEURISTIC','Kurumsal kimlik sayfası bulunamadı','No clear organization/about page found','Kullanıcı ve makine tarafında işletme bağlamı zayıflayabilir.','Business context may be weaker for users and machines.','No internal About/Hakkımızda route detected',base.href,true));if(!hasContact)add(findings,finding('TRUST-CONTACT-001','trust','medium','strong','INTERNAL_HEURISTIC','Açık iletişim yolu bulunamadı','No clear contact path found','Güven ve dönüşüm sürtünmesi artabilir.','May increase trust and conversion friction.','No contact route/mailto/tel detected',base.href,true));if(!hasPrivacy)add(findings,finding('TRUST-PRIVACY-001','trust','low','strong','INTERNAL_HEURISTIC','Gizlilik sayfası bulunamadı','No privacy page found','Veri işleyen sitelerde güven ve uyum sinyali eksik olabilir.','May weaken trust/compliance signals on sites handling data.','No privacy/KVKK route detected',base.href,true));if(/\b(article|blog|news|haber|makale)\b/i.test(trustText)&&!pages.some(p=>p.hasAuthor))add(findings,finding('TRUST-AUTHOR-001','trust','low','probable','INTERNAL_HEURISTIC','İçeriklerde yazar sinyali zayıf','Author signals appear weak','Editoryal hesap verebilirlik daha az görünür olabilir.','Editorial accountability may be less visible.','Article-like content detected without author markers',base.href,true));
const agentSignals={agentCard:agentCard.ok,openapi:openapi.ok,mcp:mcp.ok,llms:llms.ok,markdown:!!mdAlt};if(!agentCard.ok)add(findings,finding('AGENT-A2A-001','agent','info','confirmed','EXPERIMENTAL','A2A agent card bulunamadı','A2A agent card not detected','Agent-to-agent keşfi için opsiyonel yüzey yok.','Optional agent-to-agent discovery surface is absent.',`HTTP ${agentCard.status} /.well-known/agent-card.json`));if(!openapi.ok)add(findings,finding('AGENT-OPENAPI-001','agent','info','confirmed','OFFICIAL_STANDARD','OpenAPI keşif dosyası bulunamadı','OpenAPI discovery file not detected','Programatik servis keşfi sınırlı olabilir.','Programmatic service discovery may be limited.',`HTTP ${openapi.status} /openapi.json`));if(!mcp.ok)add(findings,finding('AGENT-MCP-001','agent','info','confirmed','EXPERIMENTAL','MCP endpoint bulunamadı','MCP endpoint not detected','Agent araç entegrasyonu için opsiyonel endpoint yok.','Optional endpoint for agent tool integration is absent.',`HTTP ${mcp.status} /mcp`));
const totalForms=pages.reduce((a,p)=>a+p.forms,0),totalCta=pages.reduce((a,p)=>a+p.ctaCount,0);if(totalCta===0)add(findings,finding('CONV-CTA-001','conversion','medium','probable','INTERNAL_HEURISTIC','Belirgin CTA bulunamadı','No clear CTA detected','Kullanıcının bir sonraki adımı belirsiz kalabilir.','The user’s next action may be unclear.',`0 CTA-like controls across ${pages.length} pages`,base.href,true));if(totalForms>0&&!hasContact&&totalCta===0)add(findings,finding('CONV-FLOW-001','conversion','medium','probable','INTERNAL_HEURISTIC','Dönüşüm yolu belirsiz','Conversion path is unclear','Form mevcut olsa da giriş ve takip akışı net görünmüyor.','Forms exist but entry/follow-up flow is not clear.',`${totalForms} forms; no clear CTA/contact route`,base.href,true));
const probeSet=[...new Set(pages.flatMap(p=>p.links))].slice(0,MAX_LINK_PROBES);let goodLinks=0,redirectLinks=0;for(const href of probeSet){const s=await probe(href);checked++;if(s>=200&&s<300)goodLinks++;else if(s>=300&&s<400){redirectLinks++;add(findings,finding('LINK-REDIR-001','links','low','confirmed','MEASURED','İç link yönlendirmeye gidiyor','Internal link points to a redirect','Gereksiz redirect zinciri performans ve tarama maliyeti yaratır.','Unnecessary redirects add crawl and performance cost.',`HTTP ${s} ${href}`,href,true))}else add(findings,finding('LINK-BROKEN-001','links','high','confirmed','MEASURED','Bozuk iç bağlantı','Broken internal link','Kullanıcı ve crawler akışı kesilir.','Breaks user and crawler flow.',`HTTP ${s||0} ${href}`,href,true))}
const avgBytes=Math.round(pages.reduce((a,p)=>a+p.bytes,0)/pages.length),avgScripts=Math.round(pages.reduce((a,p)=>a+p.scripts,0)/pages.length);const fieldData={coreWebVitals:'NOT_MEASURED',reason:'Public HTML fetch does not provide reliable field LCP/INP/CLS. Integrate CrUX/PageSpeed for field/lab metrics.'};
const techRules:Rule[]=[{ok:pages.every(p=>p.status<400),weight:18},{ok:pages.every(p=>!!p.title),weight:14},{ok:pages.every(p=>!!p.description),weight:10},{ok:pages.every(p=>!!p.canonical),weight:16},{ok:pages.every(p=>!p.robotsMeta.includes('noindex')),weight:16},{ok:sitemap.ok,weight:14},{ok:robots.ok,weight:12}];const crawlRules:Rule[]=[{ok:first.response.ok,weight:25},{ok:robots.ok,weight:20},{ok:sitemap.ok,weight:20},{ok:pages.length>1||home.links.length===0,weight:15},{ok:pages.every(p=>p.status<400),weight:20}];const aiRules:Rule[]=[{ok:policies.Googlebot?.allowed!==false,weight:25},{ok:policies['OAI-SearchBot']?.allowed!==false,weight:25},{ok:policies['Claude-SearchBot']?.allowed!==false,weight:20},{ok:policies.PerplexityBot?.allowed!==false,weight:20},{ok:schema.parsed.length>0,weight:10}];const llmsRules:Rule[]=[{ok:llms.ok,weight:35},{ok:llms.ok?lv.h1:null,weight:20},{ok:llms.ok?lv.summary:null,weight:10},{ok:llms.ok?lv.links.length>0:null,weight:15},{ok:!!described,weight:10},{ok:!!mdAlt,weight:10}];const schemaRules:Rule[]=[{ok:schema.parsed.length>0,weight:45},{ok:schema.invalid===0,weight:30},{ok:entityTypes.length>0,weight:25}];const perfRules:Rule[]=[{ok:avgBytes<250000,weight:35},{ok:avgScripts<=20,weight:25},{ok:pages.every(p=>p.blockingHeadScripts<=2),weight:25},{ok:pages.every(p=>p.mixedContent===0),weight:15}];const a11yRules:Rule[]=[{ok:pages.every(p=>!!p.lang),weight:20},{ok:pages.every(p=>p.imagesMissingAlt===0),weight:25},{ok:pages.every(p=>p.unlabelledInputs===0),weight:30},{ok:pages.every(p=>p.buttonsWithoutName===0),weight:25}];const secRules:Rule[]=[{ok:base.protocol==='https:',weight:20},{ok:!!hdr.get('strict-transport-security'),weight:20},{ok:!!hdr.get('content-security-policy'),weight:20},{ok:(hdr.get('x-content-type-options')||'').toLowerCase()==='nosniff',weight:15},{ok:!!hdr.get('referrer-policy'),weight:10},{ok:!!hdr.get('permissions-policy'),weight:10},{ok:pages.every(p=>p.mixedContent===0&&p.insecureForms===0),weight:5}];const trustRules:Rule[]=[{ok:hasAbout,weight:25},{ok:hasContact,weight:30},{ok:hasPrivacy,weight:20},{ok:hasTerms,weight:10},{ok:entityTypes.length>0,weight:15}];const agentRules:Rule[]=[{ok:llms.ok,weight:30},{ok:!!mdAlt,weight:20},{ok:agentCard.ok,weight:15},{ok:openapi.ok,weight:20},{ok:mcp.ok,weight:15}];const convRules:Rule[]=[{ok:totalCta>0,weight:45},{ok:hasContact,weight:35},{ok:pages.every(p=>p.insecureForms===0),weight:20}];const linkRules:Rule[]=[{ok:probeSet.length?goodLinks===probeSet.length:null,weight:80},{ok:redirectLinks===0,weight:20}];const scores:Record<Category,number>={crawl:score(crawlRules),technical:score(techRules),ai:score(aiRules),llms:score(llmsRules),schema:score(schemaRules),performance:score(perfRules),accessibility:score(a11yRules),security:score(secRules),trust:score(trustRules),agent:score(agentRules),conversion:score(convRules),links:score(linkRules)};
const overallWeights:Record<Category,number>={crawl:12,technical:14,ai:12,llms:6,schema:8,performance:10,accessibility:9,security:10,trust:7,agent:3,conversion:4,links:5};const overall=Math.round(CATEGORIES.reduce((a,c)=>a+scores[c]*overallWeights[c],0)/CATEGORIES.reduce((a,c)=>a+overallWeights[c],0));const rank:any={critical:0,high:1,medium:2,low:3,info:4};findings.sort((a,b)=>rank[a.severity]-rank[b.severity]||a.id.localeCompare(b.id));return {scanId:crypto.randomUUID(),domain:base.hostname,url:base.href,scannedAt:new Date().toISOString(),checked,overall,scores,findings,summary:{pagesDiscovered:unique.length,pagesScanned:pages.length,linksProbed:probeSet.length,averageHtmlBytes:avgBytes,averageScripts:avgScripts,schemaTypes:schema.types,llmsLinks:lv.links.length},policies,fieldData}}
